### PR TITLE
Removal of single precision constants in BUMP

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Companion PR of https://github.com/JCSDA-internal/saber/pull/69/files.
Test differences are not significant.

No impact expected on performances. BUMP NetCDF files need to be cleaned before running ctest.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
Hi @travissluka and @guillaumevernieres. Since last week, I cannot update the SOCA test reference files properly (#524, #531, #534). In the current PR, differences are small (< 1.0e-5) but larger than the prescribed tolerance (1.0e-12). I'm still using GNU 9.3.0 on my local workstation, and it was working well previously. Is there any change that could explain this new (and annoying) behavior?

**Comment by benjaminmenetrier** [comment]
I tried to install soca with the method 3. mentioned in the README.md. It worked well, tests are not failing with the `feature/double_precision_constants` branch for SABER and SOCA... so I can't figure out what's different when running with Travis CI.

**Comment by guillaumevernieres** [comment]
> I tried to install soca with the method 3. mentioned in the README.md. It worked well, tests are not failing with the `feature/double_precision_constants` branch for SABER and SOCA... so I can't figure out what's different when running with Travis CI.

Thanks @benjaminmenetrier , we'll have a look ...

**Comment by benjaminmenetrier** [comment]
I managed to reproduce the error in a Docker container on my workstation. I should be able to find the origin of the difference, no need for you to spend some time on this.

**Comment by benjaminmenetrier** [comment]
I don't really have time to dig in right now, so I just updated this PR with the correct reference files. If the differences look reasonable to you, please approve the PR and I'll merge the SABER one tomorrow.

**Comment by benjaminmenetrier** [comment]
This PR can be merged now.

**Review by guillaumevernieres — APPROVED** [review]
Merci @benjaminmenetrier

**Pull request merged**
