### PR TITLE
bring SOCA up to JEDI directory structure

### PR DESCRIPTION
**Pull request by aerorahul**
SOCA source code is now placed under src/soca, instead under src, similar to JEDI projects OOPS, UFO, IODA.

This will (hopefully) allow coupled interfaces to co-exist without stepping over each other.

Change-Id: I8f553b2ad51aa84286738ed9b94c27d722833fab

### CODE REVIEW

**Review by travissluka — APPROVED** [review]
hmm, something odd happened with the merge with develop. Changes that were actually made with the Geom cleanup PR show up as changes here.

Regardless, faced with 114 different files, my limited attention span signs off on this.

**Comment by aerorahul** [comment]
@travissluka I rebased the reorg branch on develop after the geomcleanup branch was merged into develop.  Somehow, it created a new commit (something that rebase is not supposed to do).
May be I can revert the commit, rebase again and see if this happens again.

There are 2 new files, everything else is a move and an edit in the header guard and includes.

**Comment by guillaumevernieres** [comment]
@aerorahul : Don't revert just yet, having a look right now. Probably OK as is.

**Comment by aerorahul** [comment]
I pushed another branch feature/reorg2 that removes this issue.

**Comment by guillaumevernieres** [comment]
@aerorahul : Closing this pr  (replaced by clean reorg2 branch)

**Pull request closed without merging**
