### PR TITLE
Update feature/ufs_dom from develop 2024-03-08

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Update feature/ufs_dom from develop 2024-03-08

I had to resolve a few conflicts and make a few changes, most notably:
- [Remove MOM_restart_CS from src/soca/Model/ufs/soca_mom6.F90](https://github.com/JCSDA-internal/soca/commit/45ee710bf8d470054445cebafde796428fd674ae)
- [Comment out checkpoint test in test/CMakeLists.txt](https://github.com/JCSDA-internal/soca/commit/20f30e4a746b2c9ae8c45ea64504438a423d4d58)

### Issue(s) addressed

ufs-bundle ng-godas currently broken

## Testing

- Compiled locally on @climbfuji's macOS
- CI: passed - https://github.com/JCSDA/ufs-bundle/actions/runs/8205289952/job/22441812821

## Dependencies

n/a

### CODE REVIEW

**Comment by travissluka** [comment]
what was happening with the checkpoint test?

**Comment by climbfuji** [comment]
> what was happening with the checkpoint test?

It complained that the dependency for the test target couldn't be found

**Comment by travissluka** [comment]
> > what was happening with the checkpoint test?
> 
> It complained that the dependency for the test target couldn't be found

hmm, oh well.
Changes seem reasonable

**Comment by climbfuji** [comment]
Good news is that ufs-bundle CI passed, so I'll open this up for review

**Comment by climbfuji** [comment]
Thanks @travissluka !

**Pull request merged**
