### PR TITLE
Feature/letkf factory

### PR DESCRIPTION
**Pull request by frolovsa**
## Description

-- change for gridPoint->localIncrement in oops
-- change yaml to be compatible with LETKF factory
No change of answers

## Testing

ran KF ctests under singularity

## Dependencies
waiting on the oops PR with the same branch name

### CODE REVIEW

**Comment by frolovsa** [comment]
@travissluka It looks like Travis CI is not picking up the dependence on the oops/feature/LETKF_factory. I thought that if the branches are named the same, the build will pick it up? Any idea what is up? Unless there is another reason why the build fails with: 
In file included from /jcsda/work/repo.src/soca/src/mains/LETKF.cc:10:0:
/repo.cache/oops/include/oops/runs/LETKF.h:18:10: fatal error: oops/assimilation/instantiateLETKFSolverFactory.h: No such file or directory

**Comment by guillaumevernieres** [comment]
> @travissluka It looks like Travis CI is not picking up the dependence on the oops/feature/LETKF_factory. I thought that if the branches are named the same, the build will pick it up? Any idea what is up? Unless there is another reason why the build fails with:
> In file included from /jcsda/work/repo.src/soca/src/mains/LETKF.cc:10:0:
> /repo.cache/oops/include/oops/runs/LETKF.h:18:10: fatal error: oops/assimilation/instantiateLETKFSolverFactory.h: No such file or directory

@frolovsa , very quick glance over your oops branch: Looks like you're missing your header file in 
https://github.com/JCSDA/oops/blob/feature/LETKF_factory/src/CMakeLists.txt

**Comment by frolovsa** [comment]
Thank you G.

**Comment by frolovsa** [comment]
@travissluka @shlyaeva , Looks like Soca is building now and passing checks. I have pushed changes to oops already.

**Review by shlyaeva — APPROVED** [review]

**Review by travissluka — APPROVED** [review]

**Comment by shlyaeva** [comment]
this can be merged now.

**Pull request merged**
