### PR TITLE
Feature/unsinterp gv

### LINKED ISSUE #274: Failure in inter-traj when using multiple obstypes and 0.25deg mom6
## Description
3DVAR on Hera fails in interp-traj when using multiple obstypes.

### To Reproduce:
What compilers/machines are you seeing this with? **Hera, intel19**
To reproduce the behavior:
1. Setup a simple 3DVAR at 1/4deg and at least 2 obstypes.
2. 3dvar fails in the bump routine [run_obsop](https://github.com/JCSDA/saber/blob/00a38911dd3ec68475954bf898650ebb58fcec8b/src/saber/bump/type_obsop.F90#L224) called inside of [soca_bumpinterp2d_mod.F90](https://github.com/JCSDA/soca/blob/906ca5e468748932202c91684af299fe9607e6f2/src/soca/Utils/soca_bumpinterp2d_mod.F90#L127)

## Output
No meaningful tracebacks, except that the last oops_trace seen is interp-traj.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
Implements new interp.
Answers expected anytime interp (hofx and var tests) is used.

### Issue(s) addressed
fixes #274 

## Testing

How were these changes tested? 
ctest and cycling on Hera with multiple obs types, at 1/4 degree with  mom6/cice5
 
What compilers / HPCs was it tested with?
gcc and intel

Are the changes covered by ctests?
yes

## Dependencies
Use oops branch with same name.
Waiting for [oops PR #508](https://github.com/JCSDA/oops/pull/508)

### CODE REVIEW

**Review by travissluka — CHANGES_REQUESTED** [review]
* remove the soca bump code if we're not going to us it anymore (protect our beautifully high code coverage percentage!)
* increase the `3dvar_soca` tolerance to `2e-9` in order for ctests to pass on intel19 / release

**Comment by guillaumevernieres** [comment]
>     * remove the soca bump code if we're not going to us it anymore (protect our beautifully high code coverage percentage!)
> 
Humm, I thought I did. Will look at it again.

**Review by travissluka — APPROVED** [review]
I ran the 1deg realtime system for 4 days... small differences in the rmsd stats, as would be expected... overall it doesn't seem to be breaking anything

**Comment by guillaumevernieres** [comment]
> I ran the 1deg realtime system for 4 days... small differences in the rmsd stats, as would be expected... overall it doesn't seem to be breaking anything

:+1: Thanks for checking.

**Pull request merged**
