### PR TITLE
update for VADER PR#586

### LINKED ISSUE #900: update to follow VADER #178
* see https://github.com/JCSDA-internal/vader/pull/178

### PR DESCRIPTION
**Pull request by travissluka**
## Description
* closes https://github.com/JCSDA-internal/soca/issues/900

## Testing

requires matching branches in SABER/VADER (after merging in develop)

## Dependencies

* https://github.com/JCSDA-internal/vader/pull/178
* https://github.com/JCSDA-internal/saber/pull/586

### CODE REVIEW

**Review by svahl991 — APPROVED** [review]
Yep, this looks like it'll work. I was thinking you'd need to change your call to the Vader constructor too, but you're still just using the default value for the second parameter so there's not even that.

**Comment by svahl991** [comment]
Is it a problem that the CI checks have failed on this PR? Or is that just normal for soca?

**Comment by travissluka** [comment]
> Is it a problem that the CI checks have failed on this PR? Or is that just normal for soca?

the vader branches hadn't had develop merged in at the time

**Comment by shlyaeva** [comment]
vader and saber PRs were merged; this PR can be merged now.

**Pull request merged**
