### PR TITLE
Low-res ocean grid

### LINKED ISSUE #789: Low-res ocean grid (36x17)
## Description
Ocean_hgrid_small.nc is not small enough. 

## Solution
Further subsampling along the latitudinal axis (start, end, 2) will reduce the resolution to approx. 10deg (36x17). This will speed up a handful of ctests that utilizes the small grid.

### PR DESCRIPTION
**Pull request by liuxiao37k**
## Description

This PR makes the low-res ocean grid lower in resolution: 36x35 -> 36x17, by subsampling the regular 5-deg grid (start,end,2) along both axes.

### Issue(s) addressed

- fixes #789 

Co-authored-by: @guillaumevernieres for doing:

- removed the tests that generate the small grid
- added @liuxiao37k 's soca_gridspec.small.nc to git-lfs, after editing out the NaN's ...
- updated test refs
- localization tests are failing ... might look at it next week.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Thanks for doing this @liuxiao37k .

In case you need to run the jcsda container to get the exact ref. output, here's how to this on Orion:
```console
module load singularity/3.7.1
singularity pull library://jcsda/public/jedi-gnu-openmpi-dev
singularity shell -e --bind /work/noaa/marine/:/mnt jedi-gnu-openmpi-dev_latest.sif # example only, edit the mount point 
cd into /mnt/<pathtoyoursandbox> 
```

**Comment by guillaumevernieres** [comment]
I'll let the ci run @liuxiao37k , but it will :boom: at the vertical loc ctests, I didn't get around to fixing those yet ...

**Comment by liuxiao37k** [comment]
> I'll let the ci run @liuxiao37k , but it will 💥 at the vertical loc ctests, I didn't get around to fixing those yet ...

@guillaumevernieres ouch I also just realized I shouldn't have merged the PR before a commit to fix the failing ctest. first time in my life clicking "merge" - got too excited and forgot the protocol. I am working on the failing ctest now.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Review by travissluka — APPROVED** [review]
thanks!

**Pull request merged**
