### PR TITLE
Feature/sync with gfdl

### LINKED ISSUE #480: Sync with GFDL
[See](https://github.com/JCSDA-internal/MOM6/issues/19)

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
At long last, we are synchronized with GFDL's latest and greatest ... 
This PR is using a the `main` branch of mom6, with a manual merge of the ecbuild/cmake work from our old branch `dev/master-ecbuild` to `feature/main-ecbuild`. My current plan is to rename the mom6 `feature/main-ecbuild` branch to `main-ecbuild` and make it the new mom6 default branch. Open to suggestions if you have a better idea, but merging into `dev/master-ecbuild` is full of conflict that I don't really want to resolve (we're ~7000 commits behind!). The power of procrastination.
Many thanks to @liuxiao37k for sorting out the problems on the BGC side.

Despite the many `mom6` commits, there were few issues:
- Minor adjustment in `Geometry`
- A restart checksum that we need to by-pass
- Using `ustar` in the model test fails in the forecast of length 0. This will be addressed in a different PR, `ustar` has been removed from the list of model variables that the model is tested with
- All the test output that have a dependency on the model advance step have been adjusted

### Issue(s) addressed
closes #480 

## Testing

What compilers / HPCs was it tested with? **gnu**/container

## Dependencies
Requires [MOM6 PR #23](https://github.com/JCSDA-internal/MOM6/pull/23)

## Dependencies
Requires the use of the  [mom6 feature/main-ecbuild](https://github.com/JCSDA-internal/MOM6/tree/feature/main-ecbuild) branch.

### CODE REVIEW

**Comment by liuxiao37k** [comment]
@guillaumevernieres Successfully built on Hera with -DENABLE_OCEAN_BGC=ON and -DENABLE_OCEAN_BGC=OFF, failed when -DENABLE_OCEAN_BGC if not specified in the `ecbuild` command line. 
My bad. I think we just need a simple fix [here](https://github.com/JCSDA-internal/MOM6/blob/feature/main-ecbuild/config_src/CMakeLists.txt#L13), replacing
`if ( NOT ${ENABLE_OCEAN_BGC})`
with:
`if ( NOT ENABLE_OCEAN_BGC)`
which should solve the problem.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Successfully built on Hera with -DENABLE_OCEAN_BGC=ON and -DENABLE_OCEAN_BGC=OFF, failed when -DENABLE_OCEAN_BGC if not specified in the `ecbuild` command line.
> My bad. I think we just need a simple fix [here](https://github.com/JCSDA-internal/MOM6/blob/feature/main-ecbuild/config_src/CMakeLists.txt#L13), replacing
> `if ( NOT ${ENABLE_OCEAN_BGC})`
> with:
> `if ( NOT ENABLE_OCEAN_BGC)`
> which should solve the problem.

@liuxiao37k , you can submit a simple bugfix PR online and take credit for it!

**Comment by liuxiao37k** [comment]
Dependencies: 
Require a simple bugfix in this JCSDA-internal/MOM6 [PR](https://github.com/JCSDA-internal/MOM6/pull/22).

**Comment by clouden90** [comment]
> Dependencies:
> Require a simple bugfix in this JCSDA-internal/MOM6 [PR](https://github.com/JCSDA-internal/MOM6/pull/22).

Tested with the bugfix PR on Orion using INTEL compiler. Passed.

**Review by liuxiao37k — APPROVED** [review]
all looking good. tested on Hera all passed.

**Comment by guillaumevernieres** [comment]
@travissluka , I wouldn't mind getting rid of that work soon ...

**Review by travissluka — APPROVED** [review]

**Comment by travissluka** [comment]
@guillaumevernieres update the bundle in soca-science as well to point to that mom branch ?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres update the bundle in soca-science as well to point to that mom branch ?

Yes, that too. There's also that [MOM6 PR that needs a review](https://github.com/JCSDA-internal/MOM6/pull/23).

**Pull request merged**
