### PR TITLE
Barycentric Lagrange interpolation - optional

### LINKED ISSUE #535: SOCA is broken
## Description
- Travis-ci tests are failing (ref test need updating)
- bump init is failing at higher resolution

### To Reproduce:
- Run the ctests
- Static B init fails at 1deg and higher

```console
       Setup subset Sc0
         Look for redundant points in the model grid
         Define subset Sc0
         Communicate data from model grid to subset Sc0
!!! ABORT in com_red_real_r1 on task #0283: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0270: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0198: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0141: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0001: both redundant values are different
!!! ABORT in com_red_real_r1 on task #0042: both redundant values are different
```

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
Companion PR for SABER PR https://github.com/JCSDA-internal/saber/pull/67, replaces #524.

Here some reference files are updated, because I found a bug with the previous interpolation in the mask boundary checking. Differences are minor though, since it affects a few points in the interpolation only.

closes #535

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
Tested with 1 deg global and 1/12 regional. All good, merci.

**Comment by benjaminmenetrier** [comment]
I just merged the SABER PR, this one can be merged now. I'll update the conflicting test files if I have some time today.

**Comment by travissluka** [comment]
I can update the reference answers on this now

**Comment by benjaminmenetrier** [comment]
OK, thanks @travissluka.

**Pull request merged**
