### PR TITLE
remove MakeObs app (replaced by HofX with additional yaml options)

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

MakeObs and HofX applications in oops were very similar, and to simplify maintenance, MakeObs is removed in https://github.com/JCSDA/oops/pull/806 and an option to perturb observations and to save them as "ObsValue" is added to HofX. HofX is now used instead of MakeObs.

The test reference changes are trivial (change in strings/new lines; results are not affected).

## Testing

Tested on my mac with jedi-clang/10.0.1 and jedi-mpich/3.3.1. All relevant tests passed, some not-relevant tests failed :)

## Dependencies

requires feature/remove_makeobs in oops.
waiting on https://github.com/JCSDA/oops/pull/806

### CODE REVIEW

**Comment by travissluka** [comment]
@shlyaeva SOCA suddenly stopped working on TravisCI last week. I think something completely unrelated changed in one of the upstream repos and exposed a memory bug in our code. I probably wont have time to debug until next week, so I'm ignoring this PR untill then. Don't wait for us though, feel free to carry on with the OOPS PR. We're going to live with a broken soca for a little while .

**Comment by shlyaeva** [comment]
oops PR was merged; this can be merged at any time.

**Comment by guillaumevernieres** [comment]
Ha! That's the one I should have been looking at. Zut ...

**Comment by travissluka** [comment]
I'm merging. The test failures are unrelated.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
