### PR TITLE
Parallel weak constraint and 4D-En-Var

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

This PR implements the modifications required for OOPS PR https://github.com/JCSDA/oops/pull/846.

## Testing

Usual ctests.
However, since there is no 4DEnVar in the SOCA tests, the serialization is not covered.

## Dependencies

- waiting on https://github.com/JCSDA/oops/pull/846
- waiting on https://github.com/JCSDA/saber/pull/155

### CODE REVIEW

**Comment by travissluka** [comment]
I'm assuming this can't actually be tested until the OOPS PR with `serializable` stuff is merged?

**Comment by ytremolet** [comment]
@travissluka the code that's in serializable is included in this one so you should be able to test if you are ready. There might be a failure in the writing of the ioda file at the end with 4d-en-var. I am going to open another PR with the fix for that.

**Comment by ytremolet** [comment]
oops and saber have been merged.

**Review by travissluka — APPROVED** [review]
the increment test is failing with this change (see #453). I am disabling the serialize/deserialize for `Increment` and `State` since 1) we don't need it now and 2) @guillaumevernieres and I don't have time to fix this any time soon. Pushing this through with my changes so we can get soca back to a working state.

**Pull request merged**
