### PR TITLE
New default branch for ECMWF repos 

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description

[Can be found here](https://github.com/orgs/JCSDA/teams/jedi/discussions/48).
Thanks for the head's up @mmiesch .

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@aerorahul , you will be repaid in virtual taps in the back for your kind review ... I just survived the first travis-ci failure without Travis around!!! Pfffuiii, nice dodge, 3 weeks 6 days to go.

**Review by flampouris — APPROVED** [review]

**Review by jkbk2004 — APPROVED** [review]
tested on hera and all works!

**Review by aerorahul — APPROVED** [review]
tested on my mac and works as expected.

**Comment by guillaumevernieres** [comment]
Thanks for the quick turn around! You guys rock :)

**Pull request merged**
