### PR TITLE
update reference answers for oops PR

### PR DESCRIPTION
**Pull request by travissluka**
## Description

Update answers for pending OOPS PR with same branch name.

- 3dvar answers changed because qc filters are now only being applied once, at the beginning.

## Dependencies

-  https://github.com/JCSDA/oops/pull/799 needs to be merged first

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
@travissluka: thank you! great that it now makes more sense in soca too; thank you for the feedback.

**Review by guillaumevernieres — APPROVED** [review]

**Comment by shlyaeva** [comment]
@guillaumevernieres: no no no, the corresponding oops PR wasn't merged yet (and unclear if it will be merged), so merging this would probably break your develop!

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres: no no no, the corresponding oops PR wasn't merged yet (and unclear if it will be merged), so merging this would probably break your develop!
oops. I should know better than merge stuff a 5pm ...

**Comment by ytremolet** [comment]
Do you get activity points if you merge and then revert???

**Comment by guillaumevernieres** [comment]
> Do you get activity points if you merge and then revert???

We definitely need to rethink the way we work ... Hummm ... @gibbsp 's in vacation, now's the time!

**Comment by shlyaeva** [comment]
We plan to merge the oops PR soon (tomorrow, hopefully). This soca PR was merged early, and then reverted; I think you'll need to resurrect the branch and reopen the PR.

**Pull request merged**
