### PR TITLE
Change ctests from DRIPCG to RPCG minimizer

### PR DESCRIPTION
**Pull request by fmahebert**
## Description

Per https://github.com/JCSDA-internal/oops/issues/2554

(I don't know if this appropriate in SOCA — please close if not)

### CODE REVIEW

**Comment by travissluka** [comment]
We actually use RPCG in the real world, I can handle updating it to that

**Comment by fmahebert** [comment]
Sounds good, thanks @travissluka. Let me know if you prefer to amend this PR or open a new PR to supersede this one.

**Comment by travissluka** [comment]
I'll just push to this one

**Comment by fmahebert** [comment]
✅ I approve of your changes to my PR but I can't self-approve :D

**Review by travissluka — APPROVED** [review]

**Review by shlyaeva — APPROVED** [review]

**Pull request merged**
