### PR TITLE
Add hybrid gain application

### PR DESCRIPTION
**Pull request by frolovsa**
## Description
Adds hybrid gain application and ctest

## Testing
added a ctest. 

## Dependencies
matching branch of oops

### CODE REVIEW

**Comment by travissluka** [comment]
FYI, I hope to look at this later today... we're still recovering from upstream repos  breaking everything in soca the past couple of days

**Comment by travissluka** [comment]
@frolovsa It seems you forgot to add `oops/runs/HybridGain.h` to the `CMakeLists.txt` in oops

**Comment by frolovsa** [comment]
@travissluka how about now. Sorry took me a while to get to this.

**Review by travissluka — APPROVED** [review]
👍

**Comment by shlyaeva** [comment]
Hmm, I think `oops/CMakeLists` still doesn't have `oops/src/runs/HybridGain.h` there (it may be good to add it!), but soca tests now pass. Is soca doing something different now in ways of building stuff in CI?

**Comment by frolovsa** [comment]
> Hmm, I think `oops/CMakeLists` still doesn't have `oops/src/runs/HybridGain.h` there (it may be good to add it!), but soca tests now pass. Is soca doing something different now in ways of building stuff in CI?

@shlyaeva  how about this line? 
https://github.com/JCSDA-internal/oops/blob/cb043ae271409e1240c417f5d4c165d610894128/src/CMakeLists.txt#L241

**Comment by shlyaeva** [comment]
> @shlyaeva how about this line?
> https://github.com/JCSDA-internal/oops/blob/cb043ae271409e1240c417f5d4c165d610894128/src/CMakeLists.txt#L241

Wow, I completely missed it (in fact, I was considering asking you to add it in that PR!)
🤦‍♀️ 
Thank you, and sorry for false alarm.

**Comment by shlyaeva** [comment]
Note: oops branch has been merged; this can be merged now.

**Pull request merged**
