### PR TITLE
Re-organization of RTD

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- Addition of an "Objects configuration" section, which should serve as the "common configuration"
- Re-ordered the applications from simple to less simple ... sort of
- Populated the soca_gridgen.x and Geometry as an example

### CODE REVIEW

**Comment by travissluka** [comment]
I forgot to say that the `feature/readthedocs` branch should be used because I have it hooked up to render in RTD in addition to `develop`

I changed it so that this branch is active now (https://jointcenterforsatellitedataassimilation-soca.readthedocs-hosted.com/en/feature-dontrtd/)

**Comment by flampouris** [comment]
I think that it misses two paragraphs/sections

1. An introduction to the "Objects configuration," where the object-oriented approach is described, and how it has been applied in the case of jedi/soca. By having this, it makes sense to give the "objects configuration."

2. "How to use SOCA," exactly after the "Overview" section.

Maybe as a numbered list with hyperlinks to the content of each step, e.g.

- Installation
- Ctest
- Required input files (as a checklist)
- Preparation of input files for SOCA (pointing to the "Objects configuration" section)
- Run the system
- Expected output files (as a checklist)
- Description of the output files

I think that this way, there will be enough information on 1. the components of the system and 2. how to run SOCA and understand what's happening.

**Comment by guillaumevernieres** [comment]
> I forgot to say that the `feature/readthedocs` branch should be used because I have it hooked up to render in RTD in addition to `develop`
> 
> I changed it so that this branch is active now (https://jointcenterforsatellitedataassimilation-soca.readthedocs-hosted.com/en/feature-dontrtd/)

OK, thanks @travissluka . Alternatively, make html and open is browser, assuming rtd and dependencies are installed in your machine.

**Comment by guillaumevernieres** [comment]
> I think that it misses two paragraphs/sections
> 
>     1. An introduction to the "Objects configuration," where the object-oriented approach is described, and how it has been applied in the case of jedi/soca. By having this, it makes sense to give the "objects configuration."
> 
>     2. "How to use SOCA," exactly after the "Overview" section.
> 
> 
> Maybe as a numbered list with hyperlinks to the content of each step, e.g.
> 
>     * Installation
> 
>     * Ctest
> 
>     * Required input files (as a checklist list)
> 
>     * Preparation of input files for SOCA (pointing to the "Objects configuration" section)
> 
>     * Run the system
> 
>     * Expected output files (as a checklist)
> 
>     * Description of the output files
> 
> 
> I think that this way, there will be enough information on 1. the components of the system and 2. how to run SOCA and understand what's happening.

Sounds good @flampouris . 
Wrt 1, the idea is that some (most?All?) of the sections of the yaml represent classes. So going through the classes and how they are created should cover most of the sections common to some of the yaml files on the "applications" side.

**Comment by travissluka** [comment]
@guillaumevernieres this has been open 377 days. Can we just close it and assume we'll have a documentation sprint early next year before soca release?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres this has been open 377 days. Can we just close it and assume we'll have a documentation sprint early next year before soca release?

@travissluka , yes

**Pull request closed without merging**
