### PR TITLE
Cool skin UFO implementation, part II

### LINKED ISSUE #118: Pass forcing from mom6 to soca State
To properly use the cool skin ufo, we need to pass the short/long wave, latent/sensible heat and friction velocity to the soca State.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
This is a follow up PR on the use of @HamidehGMAO 's cool skin UFO.
Added feature:

- Read ocnsfc fields from diag or restart if present 

- Apply horizontal convolution to ocnsfc

- Save increment (in add_incr)

-  Get ocnsfc state from MOM 

Possible followup PR: 

- Create convolution object specific to ocnsfc (currently sharing with ocean)

- "Push" forcing back to MOM 

closes #118

### CODE REVIEW

**Comment by travissluka** [comment]
@guillaumevernieres are you sure you committed the latest `.test` files you had, I'm getting completely different hofx for the cool skin obs.
E.g. for hofx3d
```
22: < Test     : H(x): CoolSkin nobs= 201 Min=-5.368790, Max=22.940644, RMS=17.228908
22: ---
22: > Test     : H(x): CoolSkin nobs= 201 Min=-0.469242, Max=30.268399, RMS=23.615008
```

**Comment by guillaumevernieres** [comment]
@travissluka : Sorry, I forgot to mention that you need to use @HamidehGMAO 's bugfix/coolskin_K2C_HE  UFO branch (just a switch from K to C ).
@HamidehGMAO : Are you ready to issue a UFO PR?

**Comment by HamidehGMAO** [comment]
@guillaumevernieres  Yes, I am going to make a PR right now

**Comment by travissluka** [comment]
@guillaumevernieres before I left for Halifax, I had worked on getting the surface forcing hooked back up to  our MOM6 config (it just needed to be interpolated). I should  be able to get that done this afternoon. It might be useful for me to merge that first before this PR, so that you can verify that the surface fields are being read/written correctly (since everything is just zero right now.)

**Comment by guillaumevernieres** [comment]
@travissluka : Sounds good.

**Comment by guillaumevernieres** [comment]
Will resolve conflicts in a few ...

**Review by travissluka — APPROVED** [review]
great, everything passes.

**Pull request merged**
