### PR TITLE
Groups of variables in BUMP

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Companion PR of https://github.com/JCSDA-internal/saber/pull/424

### CODE REVIEW

**Comment by svahl991** [comment]
I believe the upstream SABER PR is scheduled to be merged tomorrow. This PR is still looking for an approver. The JCSDA calendar says @travissluka is on leave this week.

**Review by guillaumevernieres — APPROVED** [review]
Thanks!

**Comment by benjaminmenetrier** [comment]
This PR can be merged now.

**Review by kbhargava — APPROVED** [review]
Thanks, looks good. I haven't run the ctests on orion as it is not being very fond of me today.

**Pull request merged**
