### PR TITLE
Get the ice and snow levels from metadata

### LINKED ISSUE #1092: reading ice files with categories and levels is broken
## Description

we merged https://github.com/JCSDA-internal/soca/pull/1062 a little too early. oops.

https://github.com/JCSDA-internal/soca/pull/1091 fixes one bug and disables the 3dvar_moreice test so we can get soca back to a working state. The ice thermo variables are not being read correctly because the number of levels is being set to 1 somewhere. The file read results in uninitialized memory (strangely the state norm looks right with gnu, but definitely wrong with intel)

```
51:  icelevs            1
51:  ncat            5
51:  shape of tmp4d          44          43           1           5           2
```

icelevs should be 7. Also, those debug prints should be removed

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #1092 

Only tested with `gnu`, but the array dimensions are correct now ... 

jedi-ci-test-select=intel

### CODE REVIEW

**Comment by travissluka** [comment]
~I'm not convinced its working right.~ If you look at the output, all the levels after the first are all zeros

Yeah definitely still not right. See intel results below

**Review by travissluka — CHANGES_REQUESTED** [review]
not working on intel
```
51: Test     :      sea_ice_category5_temperature   min=-22.0552005767822266   max=239890291858308269168826119674260996995638201361174053557517939123698397465441613273985440471640398094536817304239015572987272299351955755478866214330132699733160267235387480925670947653282275499131325358526372080368533809802886399097173177145459069773306775228998152960768561119232.0000000000000000   mean=260380836759511496478776517360851214595128244768396016015097437849034896020266191022156156432540414978929087219876771489491031336127362835589817843881185979184017000668669315264077755372104424050737450928907384806174872719486552410608412605554286915992364285985866834099906281472.0000000000000000
51: Test     :         sea_ice_category1_salinity   min=0.0000000000000000   max=923230871311566857793513102641432742980545008732530411309574599907551787641308264195119320552844469048228846435745487474713794672825284965010768068616208863471359667648209256933695846577286984013041792155641637021734251540911811280011549157342850805952379586092838964859936467582976.0000000000000000   mean=805962396587156227418397221967932088995460692308363969554340994191094190869792261935962601926070000293643359980148576354310096704664419395988139008977690244230996289821362682494001541351605466350828595753490018141300128825872650863230896128316094973120367700733617495166909677568.0000000000000000
51: Test     :         sea_ice_category2_salinity   min=0.0000000000000000   max=923230871311566857793513102641432742980545008732530411309574599907551787641308264195119320552844469048228846435745487474713794672825284965010768068616208863471359667648209256933695846577286984013041792155641637021734251540911811280011549157342850805952379586092838964859936467582976.0000000000000000   mean=915408766194085287348308012075125956343652361923894829590160318913106354959594290521082251531531109167925361866887852156489505357234100963933951020777935556485451817854272923979753444872469686719207508578293134636342106397936040798203570934036981631646563144074408808886285893632.0000000000000000
51: Test     :         sea_ice_category3_salinity   min=0.0000000000000000   max=923230871311566857793513102641432742980545008732530411309574599907551787641308264195119320552844469048228846435745487474713794672825284965010768068616208863471359667648209256933695846577286984013041792155641637021734251540911811280011549157342850805952379586092838964859936467582976.0000000000000000   mean=1026320957728404365725481193563225121514474063718133411915155879007299342879199452570494871397570616960295672080438776197562800820360877264507888467700787348357994864750151436905713344528915786738174542658282324149394250004998266960806031632106579433749664393934203743661711163392.0000000000000000
51: Test     :         sea_ice_category4_salinity   min=0.0000000000000000   max=1496928475702574479345767025059877643025161746241424525482585902941432094621243938929264006001151871003828583377696169901167555412375843482002974185694091567154922738707689548668947571126296965702838068669883440378274622582319715817751353838455510723333925144658344383030871743222775808.0000000000000000   mean=131298382319956947528978933888803608888117678385034818671203659976442039208913444217308126466224608134043584277514021671103594816714617973622350883232770446878025864850187012554488946700690905812901292886399417420065172166450130887063163137888480973538556716462801991318132303593472.0000000000000000
51: Test     :         sea_ice_category5_salinity   min=0.0000000000000000   max=1496928475702574479345767025059877643025161746241424525482585902941432094621243938929264006001151871003828583377696169901167555412375843482002974185694091567154922738707689548668947571126296965702838068669883440378274622582319715817751353838455510723333925144658344383030871743222775808.0000000000000000   mean=131298382319956947528978933888803608888117678385034818671203659976442039208913444217308126466224608134043584277514021671103594816714617973622350883232770446878025864850187012554488946700690905812901292886399417420065172166450130887063163137888480973538556716462801991318132303593472.0000000000000000
```

**Comment by guillaumevernieres** [comment]
@travissluka , I just finished testing with `gnu` and `intel`.

**Comment by travissluka** [comment]
tagging @eap for his awareness of integration tests that keep randomly failing:

https://github.com/JCSDA-internal/soca/pull/1093/checks?check_run_id=32607344065
```
  CRITICAL - /workdir/test_root/jedi-bundle/femps git clone failed:

    /usr/bin/git clone https://github.com/jcsda-internal/femps.git  /workdir/test_root/jedi-bundle/femps -q
    remote: Invalid username or password.

  fatal: Authentication failed for
  'https://github.com/jcsda-internal/femps.git/'
```

**Review by travissluka — APPROVED** [review]

**Review by kbhargava — APPROVED** [review]
Look good to me and ctests pass with GNU and intel on orion and hercules respectively. 🎉

**Pull request merged**
