### PR TITLE
Remove unused and empty Localization class

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

I am refactoring `Localization` classes in oops, and was going through the models to see if they have implementations of `Localization`.
It looks like there is an unused and empty implementation of `Localization` in soca, that perhaps could be removed? (Unless there are plans to populate it with soca specific `Localization` implementation).

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
We probably had plans ... ages ago, but here we are. So no, we won't implement a soca specific localization any time soon (or ever). 
Thanks for the clean up @shlyaeva

**Review by travissluka — APPROVED** [review]
Oooh, code coverage increase of 0.01%!

**Comment by shlyaeva** [comment]
> Oooh, code coverage increase of 0.01%!

I know! Am I awesome or am I awesome! 😆

**Comment by guillaumevernieres** [comment]
> > Oooh, code coverage increase of 0.01%!
> 
> I know! Am I awesome or am I awesome! laughing

You certainly are @shlyaeva , but it was definitely a team effort. We developed something useless for you to clean up. We're awesome too.

**Comment by shlyaeva** [comment]
This can be merged at any time; doesn't need to wait for oops PR.

**Pull request merged**
