### PR TITLE
Fix BUMP tests

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
Companion PR of https://github.com/JCSDA-internal/saber/pull/179.

Tests modifications are due to an update of mask checking procedure, to ensure reproducibility between compilers.

### CODE REVIEW

**Review by travissluka — APPROVED** [review]
thanks @benjaminmenetrier

**Comment by benjaminmenetrier** [comment]
Thanks @travissluka for the approval. Can I merge the SABER PR today? (I don't want to break your nightly builds).

**Comment by travissluka** [comment]
@benjaminmenetrier go ahead and merge. 
So long as we have a passing soca PR ready, don't worry too much about breaking the soca nightly build (you break soca far less frequently than the rest of the JEDI group 😉! )

**Comment by benjaminmenetrier** [comment]
Done, you can merge this PR.

**Pull request merged**
