### PR TITLE
Update feature/ufs_dom from develop 2023/12/12

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

With great help from @fmahebert I was able to update the soca branch feature/ufs_dom from develop and I can now compile the NG-GODAS app and the S2S app with ufs-bundle PR https://github.com/JCSDA/ufs-bundle/pull/47 (just update the soca branch name) on my macOS using apple-clang@13.1.6, openmpi@4.1.6, spack-stack@1.5.1 with fms@2023.01.

@mark-a-potts @travissluka can you please this PR before I merge it into `feature/ufs_dom`?

### CODE REVIEW

**Comment by climbfuji** [comment]
Added develop from this morning (13 dec 2023)

**Comment by shlyaeva** [comment]
@climbfuji this needs one more merge from develop (we just merged another coordinate series in oops-saber-soca, doesn't affect fv3-jedi). let me know if you'd like me to merge develop into this branch and push here.

**Review by mark-a-potts — APPROVED** [review]
I can confirm it worked for my build. I did have to add "-fPIC" to the CMAKE_FORTRAN_FLAGS in cdeps, cmeps, and cice CMakeLists.txt files of UFS, though.

**Comment by climbfuji** [comment]
> I can confirm it worked for my build. I did have to add "-fPIC" to the CMAKE_FORTRAN_FLAGS in cdeps, cmeps, and cice CMakeLists.txt files of UFS, though.

Can you create a PR for this, please?

**Review by travissluka — APPROVED** [review]
i didn't run the code, but I did a quick diff against `develop` and the merge seems reasonable

**Comment by climbfuji** [comment]
> i didn't run the code, but I did a quick diff against `develop` and the merge seems reasonable

Thanks @travissluka and @mark-a-potts for your reviews.

**Pull request merged**
