### PR TITLE
Trigger travis-ci for release/soca-1.0.0

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
What the title says.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Oops ... prep.sh does not handle "TAG" keywords in the bundle.

**Comment by travissluka** [comment]
I thought I fixed that. Maybe I fixed it in the soca-science prep

**Comment by guillaumevernieres** [comment]
> I thought I fixed that. Maybe I fixed it in the soca-science prep

Ha, ok. When using tag we have 1 less field, so ``` awk '{print $8}'``` returns `)` . Cool branch name!
Going to add `UPDATE` in front of tag ... nobody will notice.

**Comment by guillaumevernieres** [comment]
> I thought I fixed that. Maybe I fixed it in the soca-science prep

I don't know what the logic of `UPDATE TAG` would be instead of just `TAG` when checking out a tag ... but **if** it works, I'm not going to argue. I had a mix of both anyways ...

**Comment by guillaumevernieres** [comment]
... 3rd or 4th time in a row that the build stalls and is terminated.
soca-ci

Could you do a mental ctest @travissluka and merge if you don't see anything wrong?

**Comment by travissluka** [comment]
it is possible that a tag could be moved to point to a different commit, so UPDATE kinda makes sense. Though that would clearly be bad style on our part for a release tag.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
