### PR TITLE
Update obs files and yamls for Obs convention

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Followed the instructions on https://github.com/orgs/JCSDA-internal/teams/jedi-models/discussions/91 + updated `ObsSpace.yaml` (draft PR to follow) + multiple manual steps.

As mentioned in #831, some variables in obs files are not renamed because they are not yet part of `ObsSpace.yaml`; I don't plan to work on adding those.

### CODE REVIEW

**Comment by shlyaeva** [comment]
All tests are passing 🎉 
However, there are at least 5 variables that aren't renamed in the obs files and yamls, see comments in #831. I don't plan to work more on this. @travissluka, @gthompsnJCSDA up to you how you would like to address the remaining variables.

**Review by gthompsnJCSDA — COMMENTED** [review]
@shlyaeva  Did you intend to target the `develop` branch?  Shouldn't the target branch be the sprint, then sprint gets merged to develop on Tuesday?

Nevermind.  This is the "draft" PR for doing the merge on Tuesday

**Comment by shlyaeva** [comment]
For soca there was no sprint branch, this creates the sprint branch to be merged into develop on Tuesday. All updates can go directly into this branch (it's not protected in soca or fv3-jedi).

**Comment by travissluka** [comment]
thanks @shlyaeva ! I'll handle the rest (once I get spack stack compiled, been out of the office too long!)

**Comment by hga007** [comment]
Thank you! We are having problems installing spack-stack on the Mac and our Linux environment. We updated the ROMS-JEDI and can no longer compile it. We are slowly making progress. Everything is broken at the moment with the new updates.

**Comment by climbfuji** [comment]
> Thank you! We are having problems installing spack-stack on the Mac and our Linux environment. We updated the ROMS-JEDI and can no longer compile it. We are slowly making progress. Everything is broken at the moment with the new updates.

@hga007 Please let me know how we can help. We have no problems building our software environments with the new spack-stack, so I am interested to learn what's wrong and fix it. Thanks!

**Review by travissluka — APPROVED** [review]

**Review by guillaumevernieres — APPROVED** [review]
Thanks @shlyaeva and @travissluka .

**Comment by shlyaeva** [comment]
This PR can be merged now (ioda and ufo PRs were just merged).

**Pull request merged**
