### PR TITLE
Added Serializable

### PR DESCRIPTION
**Pull request by ytremolet**
## Description

Added serialization for exchanging increments and states via MPI (empty for now).

## Testing

What?

## Dependencies

JCSDA/oops#932 and this one have to be merged together.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@ytremolet  ... hug hoooo, I don't know what to say ... Does that mean we have to be nice? For how long?

**Comment by ytremolet** [comment]
@guillaumevernieres  And now I just added the correct dependency so you don't merge too early. That must be worth months of being nice!

**Review by travissluka — APPROVED** [review]

**Comment by shlyaeva** [comment]
oops branch was merged; this can now be merged too.

**Comment by guillaumevernieres** [comment]
> @ytremolet No milestones, no estimate, no issues, no epics ... Just sayin' ...

Yeah, that's because it was split off the cost function refactoring and the cost etc... are already included in that other PR. Bad....

**Pull request merged**
