### PR TITLE
Update time window configuration

### LINKED ISSUE #977: update for upstream yaml changes in OOPS#2442
update yamls for changes in https://github.com/JCSDA-internal/oops/pull/2442

### PR DESCRIPTION
**Pull request by travissluka**
## Description
- fixes https://github.com/JCSDA-internal/soca/issues/977

change to yaml to deal with upstream PRs

## Dependencies
build-group=JCSDA-internal/oops#2442
build-group=JCSDA-internal/ioda#1154
build-group=JCSDA-internal/ufo#3093

### CODE REVIEW

**Review by ctgh — APPROVED** [review]
This all looks good, thanks for adding it!

**Comment by kbhargava** [comment]
This looks fine. However, I am having trouble building this branch with GNU on orion.

**Review by guillaumevernieres — APPROVED** [review]
Thanks for the head's up again @travissluka .

**Comment by ctgh** [comment]
@kbhargava I am shortly going to update a few of the upstream repositories, which may fix the build errors.

**Comment by kbhargava** [comment]
don't know what changed but this builds fine on orion now !!

**Review by kbhargava — APPROVED** [review]

**Review by ShastriPaturi — APPROVED** [review]

**Comment by svahl991** [comment]
The "root" OOPS PR is now merged. This PR can and should merge now.

**Pull request merged**
