### PR TITLE
Update yaml files to new refactored obsdatain, obsdataout specs.

### PR DESCRIPTION
**Pull request by srherbener**
This PR make the necessary updates to YAML files according to jcsda-internal/ioda/pull/776.

Please see jcsda-internal/ioda/issues/713 for details of this change and for tracking the progress of model repo updates

### Issue(s) addressed

- partially addresses jcsda-internal/ioda/issues/713

## Acceptance Criteria (Definition of Done)

All fv3 tests pass with the new YAML configuration

## Dependencies

- [ ] merge with jcsda-internal/ioda/pull/776

### CODE REVIEW

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @srherbener!

**Review by travissluka — CHANGES_REQUESTED** [review]
I will need to merge https://github.com/JCSDA-internal/soca/pull/806 first, at which point there will be too many merge conflicts with this PR, and so whatever script was used will need to be rerun. I'll let you know when I merge that other PR (today?)

**Comment by srherbener** [comment]
> I will need to merge #806 first, at which point there will be too many merge conflicts with this PR, and so whatever script was used will need to be rerun. I'll let you know when I merge that other PR (today?)

@travissluka sounds good and thanks for the warning.

**Review by travissluka — APPROVED** [review]
Thanks @srherbener !

**Review by cmgas — APPROVED** [review]
This is good!

**Pull request merged**
