### PR TITLE
Removed empty Run class

### PR DESCRIPTION
**Pull request by ytremolet**
No need for classes that do nothing, and that might cause problems down the road. 

And I've always dreamt I would be able to contribute to soca! :-)

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Thanks for that work @ytremolet.
Finally the marine side gets some JEDI-love.

**Review by guillaumevernieres — APPROVED** [review]
Good job @ytremolet !

Student certificate

**Comment by ytremolet** [comment]
Very proud. I will frame this one!

**Comment by shlyaeva** [comment]
I want one too!

**Pull request merged**
