### PR TITLE
Merge develop in `feature/ufs_dom`

### PR DESCRIPTION
**Pull request by cmgas**
Update with develop - I couldn't test the build

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
did not test (tried but it doesn't work on the platform/compiler of choice), approving based on commit history -- just merging develop in.

**Comment by climbfuji** [comment]
I'll test it in a bit on my macos where the shared vs static linker issue does not occur (at least it didn't last time!)

**Comment by climbfuji** [comment]
What do you mean with "I don't think this works yet"?

I can compile the NG-GODAS configuration on my macOS, but the tests are failing (as before, so that is expected).

**Comment by cmgas** [comment]
At the time I was getting an error on my Mac, I have not tested since updating with the newest develop

**Review by climbfuji — APPROVED** [review]
I tested the NG-GODAS build.

**Pull request merged**
