### PR TITLE
Adds configuration to linear getvalues. 

### PR DESCRIPTION
**Pull request by cmgas**
## Description
Adds configuration to linear getvalues. Code compiles but does nothing with the configuration. Let me know if you'd like to actually use that capability.

## Dependencies
Waiting on the following PRs:

- [ ] waiting on JCSDA-internal/oops/pull/1044

### CODE REVIEW

**Comment by travissluka** [comment]
tests failing because matching branch in oops is out of date with changes in ioda?

**Comment by shlyaeva** [comment]
coding norms test is failing here.

**Comment by shlyaeva** [comment]
oops PR was merged; this PR can be merged now, once the coding norms are fixed.

**Review by travissluka — APPROVED** [review]

**Comment by travissluka** [comment]
BTW, I think  "compiles but does nothing" is the new slogan for SOCA!

**Comment by shlyaeva** [comment]
> BTW, I think "compiles but does nothing" is the new slogan for SOCA!

lol, this is my motto.

**Pull request merged**
