### PR TITLE
Feature/devolve seaice

### LINKED ISSUE #488: Devolution of sea ice DA (3d to 2d)
## Description
We(I) want to simplify how we handle sea ice DA in soca, and shift the complexity to dedicated sea-ice model interfaces. For example, @jkbk2004 is working on a [cice6 interface](https://github.com/JCSDA-internal/soca-cice6) which is eventually going to be used to initialize sea ice in the UFS and wherever cice6 is used.

## Solution
The sea-ice DA in soca should only consider 1 sea-ice category (2D fileds), aggregated from the multi categories of sis2 or cice4-5 or 6 (3D fields).

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
This proposed (imposed) feature converts the seaice DA from 3D to 2D by aggregating ice fraction, thickness and snow depth along the categories. Doing so unfortunately required quite a few changes to the test output and a few minor changes/simplification to the code. The seaice read routine is a bit convoluted and will have to be cleaned up at some point. 
A few annoying issues:
- Changing the state from 3D to 2D for the seaice variable also changed the output of the ensemble generation, and all the subsequent tests relying on it.
- We might have had a bug in the gpnorm for ssh, see [convertstate.test L12](https://github.com/JCSDA-internal/soca/blob/2741c7d7a1238fbf6256299abd995403549c04f5/test/testref/convertstate.test#L12) mean ssh=-0.274921 in develop changes to -0.246379
however, there is no difference between develop and this branch when comparing the output of the convertstate test `./Data/ocn.remapped.fc.2018-04-15T00\:00\:00Z.PT0S.nc`, and in fact, the mean in develop is wrong.

If you distrust @guillaumevernieres , which you probably should, do the following:

copy/paste the following in `test-ssh-mean.py`
```python
#!/usr/bin/env python
import netCDF4
import numpy as np

ncf=netCDF4.Dataset("./Data/ocn.remapped.fc.2018-04-15T00:00:00Z.PT0S.nc",'r')
ssh=ncf.variables['ave_ssh'][:]
ncf.close()

I=np.where(abs(ssh)>0.0)
mask=np.zeros(np.shape(ssh))
mask[I]=1.0
print(np.sum(ssh[I])/np.sum(mask))
```  
```console
$ ./test-ssh-mean.py
$ -0.2463792889278145
```
`develop` and `feature/devolve-seaice` git the same results ... No clue where the issue was.

### Issue(s) addressed
closes #488 

## Testing

How were these changes tested? **somewhat careful look at the changed output**
What compilers / HPCs was it tested with? **gnu**
Are the changes covered by ctests? **sure**

## Dependencies
@mjkagnes123 , It will probably break the sea ice DA in `soca-science`. Issue will be created "soon".

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Oops ... forgot to test with the crtm.

**Comment by guillaumevernieres** [comment]
One of the test is still failing, I'll wait for #484 to go through, since the ref tests will have to be readjusted after #484 is merged.

**Comment by mjkagnes123** [comment]
O.K.! I will wait to test it. Thanks.
________________________________

**Comment by guillaumevernieres** [comment]
To the reviewers: The :x: is due to a -0.03% reduction of the code coverage, not ctest failures. I tested this branch with `soca-science` / `mom6-sis2` on Orion, nothing crazy to report.

**Review by jkbk2004 — APPROVED** [review]
Looks good. Tested ok on Orion.

**Review by travissluka — APPROVED** [review]
.... doesnt seem to break anything

**Comment by mjkagnes123** [comment]
Checked out this branch, built and compiled the branch successfully in discover. And Ctest was ran: 


95% tests passed, 3 tests failed out of 59

Label Time Summary:
executable    =  32.33 sec*proc (19 tests)
mpi           =  32.33 sec*proc (19 tests)
script        = 106.01 sec*proc (38 tests)
soca          = 138.35 sec*proc (57 tests)

Total Test time (real) = 144.33 sec

The following tests FAILED:
	  5 - test_soca_convertstate (Failed)
	 49 - test_soca_3dvarbump (Failed)
	 54 - test_soca_3dvarfgat (Failed)
Errors while running CTest
/discover/nobackup/mkim1/SOCAGEOS/x1-devolve-seaice/soca-science/build/soca>

**Review by mjkagnes123 — APPROVED** [review]

**Pull request merged**
