### PR TITLE
Use icepack_FOUND in code CMakeLists

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Use icepack_FOUND in the code and BUILD_ICEPACK only in the bundle. This prevents other people from having to add BUILD_ICEPACK in addition to putting it in the bundle.

### Issue(s) addressed

N/A

## Testing

Icepack test builds without needing to specify 

## Dependencies

N/A

### CODE REVIEW

**Comment by travissluka** [comment]
hmm, the reference answers don't match for the test using icepack.... have we not been running that test this whole time, and @danholdaway fixed it to actually run that test!?!? oops

**Comment by Dooruk** [comment]
This works for me, should I update the test reference for "Travis" to work 😄

**Review by Dooruk — APPROVED** [review]

**Comment by travissluka** [comment]
> This works for me, should I update the test reference for "Travis" to work 😄

sure, if you could do that, that would be great.
It seems the other non-TravisCI tests are not compiling with icepack, so i'll have to fix that in a separate PR

**Comment by danholdaway** [comment]
I just pushed the ref change.

**Comment by guillaumevernieres** [comment]
That's weird that the test failed. The test ref was created with gnu and was still OK the last time I checked.

**Pull request merged**
