### PR TITLE
Revert "update reference answers for oops PR"

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Reverts JCSDA/soca#418

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]

**Comment by travissluka** [comment]
@guillaumevernieres  is clearly trying to increase his PR counts that Phil/Tom are keeping track of!

**Comment by shlyaeva** [comment]
@travissluka: lol. I was wondering what my strategy should be (e.g. leaving this comment here would probably count!) The best I've come up so far is reopening @wsmigaj's PRs as if they were mine 😆   (@wsmigaj, btw, feel free to close and open as yourself!)

**Comment by travissluka** [comment]
I'm merging, it's going to fail until the makeobs PR is merged.... and that one is going to fail until this one is merged. fun

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres is clearly trying to increase his PR counts that Phil/Tom are keeping track of!

Totally counts! (windy month, pr count has been low ...)

**Pull request merged**
