### PR TITLE
enable use of U/V

### LINKED ISSUE #836: Add (u,v) to one of the var test
## Description
EMC is adding (u,v) to the control variables. It might be useful to have this feature back and as part of the `soca` CI.

### Possible issues
- [ ] `Ana2Model` hasn't been tested in a while (Seems fine)
- [ ] missing B for u, v. (Using ens. derived B) 
- [x] #842

### PR DESCRIPTION
**Pull request by travissluka**
## Description

- closes #836

### code changes:
- `uocn` and `vocn` no longer break `SocaError`, instead a warning is issued because those variables are not on the `h` grid and so technically are not correct (deal with that another day). 
- diracs now work with u and v

### yaml / test changes
- the static 5 deg ensemble files were regenerated to include u/v perturbations
- `uocn`/`vocn` were inserted in most places where it could be added
	- anything dealing with ensembles (e.g. `3dhyb...`, `3dvarbump`, `dirac_socahyb_cov`) now have u/v increments
	- tests such as `3dvar_soca` have a u/v increment of 0, as expected, since there is no balance with u/v
- all of the `...fgat` tests now have `Ana2Model` enabled, which currently will only rotate u/v, not destagger
- I also took the opportunity to remove `hocn` from the analysis variables where it was no longer needed.

### Things that need to be done in another PR
- come up with different names for the transformed variables (there are too many different `uocn` that are named the same!)
- enable destaggering of u/v

### CODE REVIEW

**Review by liuxiao37k — APPROVED** [review]
Tested on Orion with GNU and had no issues with the ctests (both before and after merging `develop`).
I noticed a few ctests didn't have `uocn` and `vocn` inserted (e.g. 3dvar_godas, 3dvar_soca) - because u/v increments would be zeros, anyway?? I assume it was intended so am approving.

**Review by guillaumevernieres — APPROVED** [review]
Thanks @travissluka .

**Comment by travissluka** [comment]
> Tested on Orion with GNU and had no issues with the ctests (both before and after merging `develop`). I noticed a few ctests didn't have `uocn` and `vocn` inserted (e.g. 3dvar_godas, 3dvar_soca) - because u/v increments would be zeros, anyway?? I assume it was intended so am approving.

I did intend to add it to `3dvar_godas`, but oh well, it's probably best to leave it out of a couple of tests anyway, besides it is in `3dvarfgat`. `3dvar_soca` should probably go away entirely because I don't think `BkgErr` is used by anyone

**Comment by guillaumevernieres** [comment]
> > Tested on Orion with GNU and had no issues with the ctests (both before and after merging `develop`). I noticed a few ctests didn't have `uocn` and `vocn` inserted (e.g. 3dvar_godas, 3dvar_soca) - because u/v increments would be zeros, anyway?? I assume it was intended so am approving.
> 
> I did intend to add it to `3dvar_godas`, but oh well, it's probably best to leave it out of a couple of tests anyway, besides it is in `3dvarfgat`. `3dvar_soca` should probably go away entirely because I don't think `BkgErr` is used by anyone

We are still using `BkgErr` @travissluka .

**Comment by liuxiao37k** [comment]
@travissluka I showed @kbhargava yesterday our new hybrid yaml in which we indeed use `BkgErrSOCA` to read in pre-computed ensemble stddev along with `BkgErrFILT`. We tried to use SABER to do so but realized that the order of file reading and linear variable changes would be screwed up.

@kbhargava here is the yaml FYI. We are still testing it.
```
  background error:
    covariance model: hybrid
    components:
    - covariance:
        covariance model: SABER
        saber blocks:
        - saber block name: ID
          input variables: *soca_vars
          output variables: *soca_vars

        linear variable change:
          input variables: *soca_vars
          output variables: *soca_vars
          linear variable changes:

          - linear variable change name: VertConvSOCA
            Lz_min: 0.0
            Lz_mld: 0
            Lz_mld_max: 1.0
            scale_layer_thick: 5

          - linear variable change name: HorizFiltSOCA
            niter: 4
            filter variables: *soca_vars

          - linear variable change name: BkgErrFILT
            ocean_depth_min: 0   
            rescale_bkgerr: 3.0
            efold_z: 2500.0     

          - linear variable change name: BkgErrSOCA
            read_from_file: 3
            basename: {{path to ensemble stddev files}}
            ocn_filename: ocn.ensstddev.fc.2019-04-11.nc
            ice_filename: ice.ensstddev.fc.2019-04-11.nc
            remap_filename: ./bkg/MOM.res.nc
            date: *bkg_date
            t_min: 0.1
            t_max: 2.0
            t_dz:  20.0
            t_efold: 500.0
            s_min: 0.0
            s_max: 0.25
            ssh_min: 0.0   # value at EQ
            ssh_max: 0.0   # value in Extratropics
            ssh_phi_ex: 20 # lat of transition from extratropics
            cicen_min: 0.05
            cicen_max: 0.05
            hicen_min: 0.1
            hicen_max: 0.1

          - linear variable change name: BalanceSOCA
            dsdtmax: 0.1
            dsdzmin: 3.0e-6
            dtdzmin: 1.0e-6
            nlayers: 10

      weight:
        value: 1.0

    - covariance:
        covariance model: ensemble
        members from template:
          template:
            read_from_file: 1
            date: *bkg_date
            basename: {{path to ensemble files}}
            ocn_filename: MOM.res_%mem%.nc
            ice_filename: cice.res_%mem%.nc
            remap_filename: ./bkg/MOM.res.nc
            state variables: *soca_vars
          pattern: '%mem%'
          nmembers: 30
        localization:
          localization method: SABER 
          saber block:
            saber block name: BUMP_NICAS
            input variables: *soca_vars
            output variables: *soca_vars
            bump:
              datadir: ./bump
              prefix: soca_bump_loc
              method: loc
              strategy: specific_multivariate 
              load_nicas_local: true
              verbosity: main
      weight:
        value: 1.0
```

**Pull request merged**
