### PR TITLE
Feature/changevar stage1 gv

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
I'm running out of time and my next window of piece and quiet is Friday afternoon, after which I'm gone until Jan 8th. Bouncing the problem back to @danholdaway or @travissluka.

Plenty of things still not working:
- lineargetvalues test ... Not quite sure how I missed that one. I'd say it's a @travissluka problem. I updated the yaml, but it seems more involved than just that.
- variable changes within the variational applications aren't working yet, the [``vars`` argument](https://github.com/JCSDA-internal/soca/blob/12df41a20c3a1e8432e65c3a5e1b372c51370c9c/src/soca/LinearVariableChange/LinearVariableChange.cc#L94) points to nowhere. Could be a snafu in the new "updateFields" method in ``Increment``, or not ...

On the positive, the `3dvar_soca` ctest runs if you comment out all the linear variable changes (who need those anyways!!!).

### CODE REVIEW

**Comment by travissluka** [comment]
That's fine @guillaumevernieres, I can take it up. You should probably be packing and getting covid tested on friday!

**Comment by danholdaway** [comment]
@travissluka if you take a sweep and find anything I can help with let me know.

**Comment by travissluka** [comment]
FYI @guillaumevernieres @danholdaway I think I have it working. I have 3dvar passing the ctests with identical answers as before, so I'm assuming the rest of the tests will work when I update the yamls. I'll issue a PR tomorrow

**Comment by danholdaway** [comment]
Nice, thanks @travissluka.

**Pull request closed without merging**
