### PR TITLE
Adapt to Distribution yaml change

### PR DESCRIPTION
**Pull request by shlyaeva**
See details in https://github.com/JCSDA-internal/ioda/pull/599.

### Dependencies
- https://github.com/JCSDA-internal/oops/pull/1658
- https://github.com/JCSDA-internal/ioda/pull/599
- https://github.com/JCSDA-internal/ufo/pull/1887

### CODE REVIEW

**Review by srherbener — APPROVED** [review]

**Review by travissluka — APPROVED** [review]
thanks @shlyaeva !

**Comment by shlyaeva** [comment]
Ci is failing with:
> - Configuring done
CMake Error at /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:302 (add_library):
  Target "soca" links to target "NetCDF::NetCDF_CXX" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  /usr/local/share/ecbuild/cmake/ecbuild_add_library.cmake:657 (ecbuild_add_library_impl)
  src/soca/CMakeLists.txt:22 (ecbuild_add_library)

I am guessing this is a result of merging https://github.com/JCSDA-internal/saber/pull/171 which added "NetCDF::NetCDF_CXX" dependency to saber, and this error would also show up in develop CI. I am not sure how to fix it here, @travissluka, @benjaminmenetrier do you have an idea?

**Comment by shlyaeva** [comment]
Apologies for not checking on this. Every time any of the generic repos adds a new dependency in CMakeLists we should make sure it works for downstream repos. Tagging @climbfuji too (Dom: saber just added a NetCDF::NetCDF_CXX dependency).

**Comment by travissluka** [comment]
FYI, new dependencies like that need to be added to the `*-import.cmake.in` files, e.g. see https://github.com/JCSDA-internal/ioda/pull/587/files

**Comment by climbfuji** [comment]
Thanks, yes, we’ll need to get rid of the netcdf-cxx4 dependencies in the mid-term.

**Comment by shlyaeva** [comment]
> FYI, new dependencies like that need to be added to the *-import.cmake.in files, e.g. see https://github.com/JCSDA-internal/ioda/pull/587/files

@travissluka I think it was done in saber: https://github.com/JCSDA-internal/saber/pull/171/files . Does it need to be added somewhere else too?

**Comment by shlyaeva** [comment]
Ready for merge now (oops, ioda, ufo were merged).

**Pull request merged**
