### PR TITLE
Multiple geometries

### LINKED ISSUE #352: Handle fms hard coded "input.nml" to allow for multiple geometries
## Description
fms initializes variables from namelists from the hard coded file name "input.nml". 

## Solution
Try to keep the code backward compatible: Allow for the use of "input.nml" as default name. 
New feature to be added: Allow a different naming for "input.nml" passed from the configuration, copy or link at run-time

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
One step closer to be able to use multiple geometries. Despite the large number of files touched, the new features are confined in the Geometry class. Most of the files were touched to update the geometry configuration in the yaml files.

**New features:**
- Addition of a test to create a coarse geometry by sub-sampling the existing MOM6 netcdf files
- An fms struct to handle the hard-coded `input.nml`
- `input.nml` in the scratch directory is now a **protected name** This is going to break our scripts for GODAS (pinging @flampouris and @jkbk2004 ), the real time SOCA and our simple regular cycling scripts in soca. None of these issues are addressed in this work. 

... and just to be sure the message is received:
**THE LOCATION OF THE `input.nml` NAMELIST IS NOW REQUIRED IN THE GEOMETRY PART OF THE YAML FILES.**

Is a change of answers expected from this PR? **NO**

**Issues to debate:**
- I went against backward compatibility, in the long run we should assume that we will need multiple input.nml, thus having to remove the one in the scratch directory. It is safer to stage it from elsewhere. This is how @danholdaway implemented it for fv3-jedi, and I can't think of a better solution, short of modifying fms. 
- I added a test to sub-sample some of the mom6 files that we use, but it's slow (~4-5 sec on my computer), they could be added to the repo instead. 
- Meaning of life?

### Issue(s) addressed
closes #352 

## Testing

How were these changes tested? **Addition of a test for a coarser grid**
What compilers / HPCs was it tested with? **gcc debug/release**
Are the changes covered by ctests? **yes**

## Dependencies
**NONE**

### CODE REVIEW

**Comment by aerorahul** [comment]
changes look good to the eye.
will do a deep dive and test later today.

I am ok with the sub-sampling script. This is done in development-mode only.  I am against increasing the size of the repo unnecessarily.

**Review by aerorahul — APPROVED** [review]
I don't like the symlink in the C++ code, but there is no good solution in the short term.
Other than that, all tests pass for me.

**Review by clouden90 — APPROVED** [review]
Just tested this and it works with the prototype convert app.

**Review by travissluka — APPROVED** [review]

**Comment by danholdaway** [comment]
For fv3-jedi we also need to stage the input.nml in the Model class. Are you doing initialization of mom6 there because that might require a different input.nml file, for example if you were doing multiple outer loops with varying resolution.

**Comment by guillaumevernieres** [comment]
> For fv3-jedi we also need to stage the input.nml in the Model class. Are you doing initialization of mom6 there because that might require a different input.nml file, for example if you were doing multiple outer loops with varying resolution.

Thanks for the info @danholdaway, yes, we are (keeping your tip in a fuzzy corner of my mind). Probably some future work for @LorentzSluka.

**Pull request merged**
