### PR TITLE
Seaice mask removal

### LINKED ISSUE #263: Remove the sea-ice mask in B
**Description**
The background based mask in the sea-ice B creates issues  when using an ensemble for the background error.

 **Solution**
Use the same mask as the ocean for sea-ice.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
See issue #263: The sea-ice mask in B is removed, which changes all the tests making use of bump.
 
What bug does it fix, or what feature does it add? **Not a bug But also not a feature**
Is a change of answers expected from this PR? **Yes**

### Issue(s) addressed
- closes #263 
- May address an issue observed in #262 

## Testing
How were these changes tested? **ctest only**
What compilers / HPCs was it tested with?**gcc**
Are the changes covered by ctests? **yes**

## Dependencies
None

### CODE REVIEW

**Review by aerorahul — COMMENTED** [review]
@guillaumevernieres 
Can you explain why answers change?  Is it because a different mask is being applied?

**Comment by travissluka** [comment]
@aerorahul yes. Due to the different mask, enspert will create different answers, which of course effects everything downstream

**Comment by guillaumevernieres** [comment]
... And the sea-ice mask was also fed to bump. So the correlation operator is different.

**Review by travissluka — CHANGES_REQUESTED** [review]
remove `i`,`j` at `soca_covariance_mod.F90` (line 66) as they are no longer used now.

I'm getting some nice divide by zeros in staticbinit with intel19 debug. I'm looking into it, might be a saber problem.

**Comment by travissluka** [comment]
hmm, weird, intel19 debug throws a div by zero in the nicas normalization for the second horiz_convol that is created (in this case the ice, but if I switch the calls so that ice is created first, then the div by zero occurs in the ocean). Weird

**Comment by guillaumevernieres** [comment]
image
Blame the rest of the world and move on?

**Comment by travissluka** [comment]
@guillaumevernieres I found where the bug is occurring in saber, but when I try to debug with print statements the bug goes away :thinking: . Probably a compiler bug, move along. 

Fix the i,j variable issue and we can merge

**Review by travissluka — APPROVED** [review]

**Pull request merged**
