### PR TITLE
ATLAS interface

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Update of the geometry, increment and covariance classes: ATLAS objects are now used to pass data to SABER/BUMP. A specific case is made for `cicen` and `hicen` variables, which are passed into the ATLAS fieldset as separate 2D fields (to be consistent with the previous implementation). As a consequence,  variable names with the level appended after `cicen` or `hicen` have to be specified in the BUMP sections of the yaml files. I'm not very happy with this solution, but it's the cleaner one I have to get the same results.

### Issue(s) addressed

Do no use the deprecated `unstructured_grid` type anymore, solve issue #372.
I'll finally be allowed to remove the deprecated BUMP interfaces!

## Testing

Should not change the ctest results.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
> [...]
> Update of the geometry, increment and covariance classes: ATLAS objects are now used to pass data to SABER/BUMP. A specific case is made for `cicen` and `hicen` variables, which are passed into the ATLAS fieldset as separate 2D fields (to be consistent with the previous implementation). As a consequence, variable names with the level appended after `cicen` or `hicen` have to be specified in the BUMP sections of the yaml files. **I'm not very happy with this solution, but it's the cleaner one I have to get the same results.**
> [...]

:+1: thanks for doing that @benjaminmenetrier . 
I agree with your highlighted comment, but I don't foresee a case where we will have more than 5 categories for our testing, so I think we will survive! Is this really a draft?

**Comment by benjaminmenetrier** [comment]
I would like to see if I can simplify the yaml files a bit, but it's minor stuff, and I'll do it on Monday. You can consider this PR as open.

**Comment by benjaminmenetrier** [comment]
OK, now I think this PR is ready for review and merge. Could anyone do a performance test to compare `develop` and this branch?

**Comment by guillaumevernieres** [comment]
> OK, now I think this PR is ready for review and merge. Could anyone do a performance test to compare `develop` and this branch?

@benjaminmenetrier , I will look at it today.

**Comment by guillaumevernieres** [comment]
## develop
```
OOPS_STATS oops::ErrorCovariance::ErrorCovariance              :      797.214 ms       1        797.214 ms/call
OOPS_STATS oops::ErrorCovariance::doInverseMultiply            :        1.517 ms       2         0.7585 ms/call
OOPS_STATS oops::ErrorCovariance::doMultiply                   :      1077.49 ms       4        269.374 ms/call
OOPS_STATS oops::ErrorCovariance::~ErrorCovariance             :        6.858 ms       1          6.858 ms/call
```

## feature/atlas_interface
```
OPS_STATS oops::ErrorCovariance::ErrorCovariance               :      778.459 ms       1        778.459 ms/call
OOPS_STATS oops::ErrorCovariance::doInverseMultiply            :        1.592 ms       2          0.796 ms/call
OOPS_STATS oops::ErrorCovariance::doMultiply                   :       1112.1 ms       4        278.026 ms/call
OOPS_STATS oops::ErrorCovariance::~ErrorCovariance             :        7.166 ms       1          7.166 ms/call
```

Tested at 1 deg resolution, `doMultiply` is slightly slower. Was that expected @benjaminmenetrier ?

**Comment by benjaminmenetrier** [comment]
Hi @guillaumevernieres, I get similar timings for `develop` and `feature/atlas_interface` on my workstation. I'm not sure timings are very reliable for such small configurations (2520 grid-points). Could you try again with a higher resolution configuration?

**Comment by benjaminmenetrier** [comment]
It took me a few hours to find out why `test_soca_addincrement` was failing with the ATLAS interface, which should not have any impact on this test... Actually, some arrays used to compute the geostrophic u/v had uninitialized values in halo D (which were set to NaN with this branch). Initializing the whole array to 0 solved the issue.

**Comment by travissluka** [comment]
Thanks @benjaminmenetrier !!

One small thing is that I prefer to use forward declarations instead of `#include` wherever possible when inside a soca `.h` file. This decreases the chances of cascading cache misses when recompiling (probably saving me several _seconds_ of compile time... well worth it!).

I pushed a commit with the changes just now, but it seems github is having server issues.... waiting for that to show up and travisci tests to rerun

**Review by guillaumevernieres — APPROVED** [review]
re-approving. Thanks again @benjaminmenetrier .

**Comment by benjaminmenetrier** [comment]
Thanks @travissluka, this kind of C++ subtleties is still above my coding level...

**Review by travissluka — APPROVED** [review]
tested on gcc and intel19, looks good.

**Pull request merged**
