### PR TITLE
use MODEL and OBS (ufo::ObsTraits) traits

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

https://github.com/JCSDA/oops/pull/703 splits MODEL trait into MODEL and OBS trait.
This PR contains changes needed to make soca work with this: remove obs-related classes from soca::Trait, use ufo::UfoTrait as OBS trait.
I have also removed some unused test source files related to obs.

## Testing

tested on orion with jedi/intel-2019.5_openmpi-4.0.2, all tests passed except  test_soca_convertstate (which I assume fails for reason unrelated to this PR)

## Dependencies

Depends on feature/template_model_obs branches in oops (https://github.com/JCSDA/oops/pull/703), saber (https://github.com/JCSDA/saber/pull/119) and ufo (https://github.com/JCSDA/ufo/pull/1124).

- waiting on https://github.com/JCSDA/oops/pull/703
- waiting on https://github.com/JCSDA/saber/pull/119
- waiting on https://github.com/JCSDA/ufo/pull/1124

### CODE REVIEW

**Review by ytremolet — APPROVED** [review]
Looks good.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by shlyaeva** [comment]
I've made some changes in ufo (rename UfoTrait->ObsTraits and put back template parameter on instantiateObsFilterFactory, explanation here: https://github.com/JCSDA/ufo/pull/1124#issuecomment-647015611), hence more changes here.

**Comment by shlyaeva** [comment]
ready for merge.

**Comment by travissluka** [comment]
@ytremolet approved a soca PR?!? what other crazy things have happened while I was gone??

**Comment by shlyaeva** [comment]
@travissluka: lol, the other crazy things is Anna issuing PRs in soca (and even somewhat following the template!)

**Pull request merged**
