### PR TITLE
Pass ObsTopLevelParameters instead of a Configuration to the constructor of ioda::ObsSpace

### LINKED ISSUE #625: Develop fails to compile
## Description
Looks like soca got out of sync with ufo? Here is the message i get when trying to compile on orion with GNU.

```
/home/sfrolov/work/jedi/src/soca/develop/bundle/soca/src/soca/GetValues/GetValues.cc: In member function ‘void soca::GetValues::getValuesFromFile(const ufo::Locations&, const oops::Variables&, ufo::GeoVaLs&) const’:
/home/sfrolov/work/jedi/src/soca/develop/bundle/soca/src/soca/GetValues/GetValues.cc:94:46: error: no matching function for call to ‘ioda::ObsSpace::ObsSpace(eckit::LocalConfiguration&, const eckit::mpi::Comm&, util::DateTime&, util::DateTime&, const eckit::mpi::Comm&)’
   94 |                           oops::mpi::myself());
      |                                              ^
In file included from /home/sfrolov/work/jedi/src/soca/develop/bundle/soca/src/soca/GetValues/GetValues.cc:10:
/home/sfrolov/work/jedi/build/soca/develop/ioda/include/ioda/ObsSpace.h:139:9: note: candidate: ‘ioda::ObsSpace::ObsSpace(const ioda::ObsSpace&)’
  139 |         ObsSpace(const ObsSpace &);
      |         ^~~~~~~~
/home/sfrolov/work/jedi/build/soca/develop/ioda/include/ioda/ObsSpace.h:139:9: note:   candidate expects 1 argument, 5 provided
/home/sfrolov/work/jedi/build/soca/develop/ioda/include/ioda/ObsSpace.h:136:9: note: candidate: ‘ioda::ObsSpace::ObsSpace(const Parameters_&, const eckit::mpi::Comm&, const util::DateTime&, const util::DateTime&, const eckit::mpi::Comm&)’
  136 |         ObsSpace(const Parameters_ & params, const eckit::mpi::Comm & comm,
      |         ^~~~~~~~
/home/sfrolov/work/jedi/build/soca/develop/ioda/include/ioda/ObsSpace.h:136:38: note:   no known conversion for argument 1 from ‘eckit::LocalConfiguration’ to ‘const Parameters_&’ {aka ‘const ioda::ObsTopLevelParameters&’}
  136 |         ObsSpace(const Parameters_ & params, const eckit::mpi::Comm & comm,
      |                  ~~~~~~~~~~~~~~~~~~~~^~~~~~
[ 92%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/Geometry/soca_geom_mod.F90.o
[ 92%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/Transforms/Balance/soca_ksshts_mod.F90.o
[ 92%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/Transforms/Balance/soca_kst_mod.F90.o
[ 92%] Building Fortran object soca/src/soca/CMakeFiles/soca.dir/Utils/soca_omb_stats_mod.F90.o
make[2]: *** [soca/src/soca/CMakeFiles/soca.dir/GetValues/GetValues.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [soca/src/soca/CMakeFiles/soca.dir/all] Error 2
make: *** [all] Error 2
```

### To Reproduce:
Trying to build develop brunch of soca/bundle on orion. 

modules loaded
```
export JEDI_OPT=/work/noaa/da/grubin/opt/modules
module use $JEDI_OPT/modulefiles/core
module load jedi/gnu-openmpi

Currently Loaded Modules:
  1) git/2.28.0        7) zlib/1.2.11         13) hdf5/1.12.0           19) eigen/3.3.7           25) fckit/ecmwf-0.9.2
  2) git-lfs/2.11.0    8) udunits/2.2.28      14) pnetcdf/1.12.1        20) bufr/noaa-emc-11.5.0  26) atlas/ecmwf-0.24.1
  3) python/3.7.5      9) gsl_lite/0.37.0     15) netcdf/4.7.4          21) pybind11/2.7.0        27) jedi/gnu-openmpi/10.2.0
  4) gcc/10.2.0       10) lapack/3.8.0        16) nccmp/1.8.7.0         22) cmake/3.18.1
  5) jedi-gnu/10.2.0  11) openmpi/4.0.4       17) pio/2.5.1-debug       23) ecbuild/ecmwf-3.6.1
  6) szip/2.1.1       12) jedi-openmpi/4.0.4  18) boost-headers/1.73.0  24) eckit/ecmwf-1.16.0
```

### LINKED ISSUE #628: Reference output related to bump has changed
## Description
What the title says.

### PR DESCRIPTION
**Pull request by wsmigaj**
## Description

The aim of this PR is to fix the build error reported in #625.

### Issue(s) addressed

- fixes #625
- fixes #628 

## Testing

I tried to test them using Travis CI. However, CMake fails with the following error:
```
CMake Error at src/CMakeLists.txt:561 (set_property):

  set_property given TEST names that do not exist:

    test_util_signal_trap
```

I don't think it's related to this PR, though.

## Dependencies

None

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Thanks for doing that @wsmigaj , we'll look into the build issue today.

**Comment by shlyaeva** [comment]
Travis CI for soca fails on making oops with log:

> -- [oops] (1.1.0) [abffb7c]
-- Tests have been disabled
...
CMake Error at src/CMakeLists.txt:561 (set_property):
  set_property given TEST names that do not exist:
    test_util_signal_trap

I'm guessing the problem is that tests are disabled. Is there a way to check if tests were disabled and not set_property in that case? @rhoneyager @travissluka.

**Comment by guillaumevernieres** [comment]
Some issues with the test output, presumably unrelated to that pr. Looking into it right now.

**Review by guillaumevernieres — APPROVED** [review]
Thanks @wsmigaj for doing this! 
(I took the liberty to push updates to the ref tests).

**Comment by guillaumevernieres** [comment]
Code cov is failing when the tests are OK now ...

**Review by shlyaeva — APPROVED** [review]

**Review by frolovsa — APPROVED** [review]

**Review by travissluka — APPROVED** [review]

**Pull request merged**
