### PR TITLE
Anisotropic functions

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
Companion PR of https://github.com/JCSDA-internal/saber/pull/164.

### CODE REVIEW

**Comment by benjaminmenetrier** [comment]
This companion PR is a bit bigger than initially planned, because I removed some deprecated interfaces from BUMP. SOCA was the only user for these interfaces, I think it was time to replace them. Also, the GC99 function is not available from BUMP anymore, but it is available from OOPS.

Reference changes look good to me.

**Review by travissluka — APPROVED** [review]
Thanks @benjaminmenetrier!

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by shlyaeva** [comment]
this PR can be merged now (saber was merged).

**Pull request merged**
