### PR TITLE
update yamls to adapt to oops/pull/2434 

### LINKED ISSUE #985: adapt to oops/pull/2434
- see https://github.com/JCSDA-internal/oops/pull/2434

### PR DESCRIPTION
**Pull request by travissluka**
## Description
- closes #985 

update yamls for pending oops PR
FYI @guillaumevernieres @ShastriPaturi , you'll probably have to make a similar change in your workflow

## dependencies

build-group=https://github.com/JCSDA-internal/oops/pull/2434

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Review by ShastriPaturi — APPROVED** [review]
Approving it out of turn.

**Review by leungtszyan — CHANGES_REQUESTED** [review]
I can see there is at least one other file (`test/testinput/3dvar_single_ob.yaml`) that hasn't implemented the change.  Please check through all the test YAML files again.

**Comment by leungtszyan** [comment]
Thanks for pushing the change.  One more thing: the `variational.iterations[n].online diagnostics.increment` section also needs to be changed in a similar way ([example](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/3dhyb.yml#L153)), and I think there are multiple files that have this section in the YAML configuration.

**Comment by travissluka** [comment]
> Thanks for pushing the change. One more thing: the `variational.iterations[n].online diagnostics.increment` section also needs to be changed in a similar way ([example](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/3dhyb.yml#L153)), and I think there are multiple files that have this section in the YAML configuration.

the ctests pass, the yaml files for all of the active test have already been updated. Anything left is not a test being exercised. Thank you for taking a look though.

**Review by leungtszyan — APPROVED** [review]
> Thanks for pushing the change. One more thing: the variational.iterations[n].online diagnostics.increment section also needs to be changed in a similar way ([example](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/3dhyb.yml#L153)), and I think there are multiple files that have this section in the YAML configuration.

Sorry I meant to refer to [this example](https://github.com/JCSDA-internal/soca/blob/develop/test/testinput/3dvar_zero_ob.yml#L83) instead of the one hyperlinked above.  Anyway, thanks for letting me know that this is not an active test.  I can indeed see this in the `CMakeLists.txt` file.  However, I would recommend that you update that YAML file as well, so that when the time comes for the test to be activated, the build could proceed smoothly.  That being said, I am approving this PR in its current form, as it's not expected to break the existing tests as you said.

**Comment by shlyaeva** [comment]
oops PR was merged, this is ready to merge now.

**Review by kbhargava — APPROVED** [review]

**Pull request merged**
