### PR TITLE
Remove validation options from OOPS Applications

### PR DESCRIPTION
**Pull request by ytremolet**
## Description

See JCSDA-internal/oops#2794 and JCSDA-internal/oops#2795

## Dependencies

build-group=JCSDA-internal/oops#2795
build-group=JCSDA-internal/saber#979
build-group=JCSDA-internal/ioda#1391
build-group=JCSDA-internal/ufo#3548
build-group=JCSDA-internal/fv3-jedi#1308

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by travissluka** [comment]
fyi @guillaumevernieres , in case you have any custom applications sitting on the gdas side

**Review by travissluka — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
> fyi @guillaumevernieres , in case you have any custom applications sitting on the gdas side

Thanks for the heads up @travissluka , yes, we do.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by ytremolet** [comment]
The OOPS PR is merged.

**Pull request merged**
