### PR TITLE
find_package(NetCDF)

### PR DESCRIPTION
**Pull request by aerorahul**
Change-Id: Ie0a9fc4db0686a04d5045381ea66bad50767744a

## Description

SOCA was making use of the NetCDF Fortran library, but the package was not being explicitly being found.  It was probably relying on the dependencies to find it.  This PR makes it explicit.

It makes sure that the include path of NetCDF includes are before the system ones (in the case of using modules).  This was causing an issue on my OSX platforms.

Is a change of answers expected from this PR? -- No.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!) -- Sue me!

## Testing

How were these changes tested? -- ctest
What compilers / HPCs was it tested with? -- Intel & GNU / OSX and Discover
Are the changes covered by ctests? (If not, tests should be added first.) -- Not necessary

## Dependencies

None

Do PRs in upstream repositories need to be merged first?
None

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@aerorahul : You've been served!

**Review by travissluka — APPROVED** [review]

**Comment by travissluka** [comment]
@guillaumevernieres I won't merge this, https://github.com/JCSDA/MOM6/pull/8 and https://github.com/JCSDA/MOM6_DA_hooks/pull/2 until you confirm Hera is cool with it, just to be safe. I know Hera gets grumpy

**Review by guillaumevernieres — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres I won't merge this, [JCSDA/MOM6#8](https://github.com/JCSDA/MOM6/pull/8) and [JCSDA/MOM6_DA_hooks#2](https://github.com/JCSDA/MOM6_DA_hooks/pull/2) until you confirm Hera is cool with it, just to be safe. I know Hera gets grumpy

Too late ... Looks like we already have issues on Hera.

**Comment by flampouris** [comment]
Testing on Hera...

**Comment by travissluka** [comment]
oops, approved too early. It's not working in my intel19 container now on my desktop. It should be

`find_package( NetCDF REQUIRED COMPONENTS Fortran )`

not `F90`

**Pull request merged**
