### PR TITLE
yaml changes to work with pending ufo PR

### LINKED ISSUE #233: make soca work with pending ufo pr
https://github.com/JCSDA/ufo/pull/729

### PR DESCRIPTION
**Pull request by travissluka**
changes to work with https://github.com/JCSDA/ufo/pull/729
testing requires ufo branch of matching name, don't merge until ufo PR is merged 

within the ObsSpace I moved the variable name out into a yaml reference, so that I don't have to repeat the name so many darn times in the file

closes #233 

includes a small change to the travisCI scripts to get this PR to work. Turns out the `feature/variable` branch was accidentally matching `feature/variable2` in ioda because I didn't pay attention to the regex lecture in my college programming classes

### CODE REVIEW

**Comment by travissluka** [comment]
...hmm, seems I broke something in the TravisCI config... working on it

**Review by shlyaeva — APPROVED** [review]
didn't run tests, but changes look right. thank you!

**Review by guillaumevernieres — APPROVED** [review]

**Comment by travissluka** [comment]
@guillaumevernieres @flampouris once this gets merged (likely today) emc's yaml files in soca-config will need to be similarly updated in order to work with the `release/stable-nightly` branch of the bundle

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres @flampouris once this gets merged (likely today) emc's yaml files in soca-config will need to be similarly updated in order to work with the `release/stable-nightly` branch of the bundle

OK, thanks for the heads up.

**Comment by flampouris** [comment]
Thanks, Travis!

**Pull request merged**
