### PR TITLE
fix problems with coding norms

### PR DESCRIPTION
**Pull request by travissluka**
I was getting tired of always seeing the soca coding norm test fail

### CODE REVIEW

**Comment by aerorahul** [comment]
@travissluka Bravo! How many times are you going to keep this up?

**Review by aerorahul — APPROVED** [review]
approved.

**Comment by travissluka** [comment]
from now on, this means PRs are denied if coding norm test fails... :-)

**Comment by shlyaeva** [comment]
@travissluka, beware anyone can merge a pull request anyway :)

**Pull request merged**
