### PR TITLE
By-pass geom init in the cloning of geometry 

### LINKED ISSUE #171: Incorrect clone of geometry
https://github.com/JCSDA/soca/blob/8a253b64e593f0e80d23bebd27b3427240787de6/src/soca/Geometry/soca_geom_mod.F90#L132

Initializing does not make it a clone!

### PR DESCRIPTION
**Pull request by guillaumevernieres**
closes #171 
- In geom clone: Replace the call to geom initialization by a pointer association.
- Turned on "check-for-useless-spaces" in my editor, so some people would get off my case!

code changes are now included in #172

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
that wasn't hard at all!

**Review by travissluka — APPROVED** [review]
... but without the end-of-line spaces what will we complain about now??

**Comment by aerorahul** [comment]
@guillaumevernieres In the hopes of not making the PR #172 excruciatingly difficult (conflicts will arise), can we fold the necessary changes of this PR #173 into #172? 
Thanks!

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres In the hopes of not making the PR #172 excruciatingly difficult (conflicts will arise), can we fold the necessary changes of this PR #173 into #172?
> Thanks!

@aerorahul : Sounds good to me, considering that most of this pr is about removing spaces ...

**Pull request closed without merging**
