### PR TITLE
bugfix for intel

### PR DESCRIPTION
**Pull request by aerorahul**
Intel compiler demands to be a pointer instead of a target.

Change-Id: I6570360d757b2ae03c69f74af761bd5c21873e69

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@aerorahul : This was addressed in an other PR ... I think we talked about it a while ago.

**Comment by aerorahul** [comment]
@guillaumevernieres you are correct. There is a branch feature/intel-fix, but no PR.
I'll issue a PR from there and close this, if that is preferred.

**Comment by guillaumevernieres** [comment]
@aerorahul : Never mind, I don't see the fix in any of the other pr ...

**Comment by guillaumevernieres** [comment]
@aerorahul : nope, that pr is fine! keep it.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
