### PR TITLE
Remove Geometry::latlon method

### PR DESCRIPTION
**Pull request by fmahebert**
## Description

Companion to OOPS PR https://github.com/JCSDA-internal/oops/pull/2628

This companion can be merged anytime after the OOPS PR is merged — it's deleting soca code that OOPS will no longer call.

## Testing

Ran soca unit tests on Orion+GNU

## Dependencies

build-group=https://github.com/JCSDA-internal/oops/pull/2628
build-group=https://github.com/JCSDA-internal/saber/pull/844

### CODE REVIEW

**Review by travissluka — APPROVED** [review]
Woo, deleting more code  🎉

**Review by kbhargava — APPROVED** [review]
Looks good.

**Comment by hga007** [comment]
@fmahebert: Thank you for the PR.  I got the following error during compilation:

```
/home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/oops/src/oops/interface/LinearObsOperator.h(137): error #165: too few arguments in function call
    oper_->setTrajectory(gvals.geovals(), aux.obsauxcontrol());
                                                             ^
          detected during:
            instantiation of "void oops::LinearObsOperator<OBS>::setTrajectory(const oops::LinearObsOperator<OBS>::GeoVaLs_ &, const oops::LinearObsOperator<OBS>::ObsAuxControl_ &) [with OBS=ufo::ObsTraits]" at line 216 of "/home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/oops/src/test/interface/LinearObsOperator.h"
            instantiation of "void test::testLinearity<OBS>() [with OBS=ufo::ObsTraits]" at line 569 of "/home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/oops/src/test/interface/LinearObsOperator.h"
            instantiation of "void test::LinearObsOperator<OBS>::register_tests() const [with OBS=ufo::ObsTraits]" at line 557 of "/home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/oops/src/test/interface/LinearObsOperator.h"
            instantiation of "test::LinearObsOperator<OBS>::LinearObsOperator() [with OBS=ufo::ObsTraits]" at line 14 of "/home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/ufo/test/mains/TestObsOperatorTLAD.cc"

compilation aborted for /home/arango/ocean/repository/git/roms-jedi/Bundle_latlon/ufo/test/mains/TestObsOperatorTLAD.cc (code 2)
make[2]: *** [ufo/test/CMakeFiles/test_ObsOperatorTLAD.x.dir/build.make:76: ufo/test/CMakeFiles/test_ObsOperatorTLAD.x.dir/mains/TestObsOperatorTLAD.cc.o] Error 2
make[2]: Leaving directory '/home/arango/ocean/repository/git/roms-jedi/build_latlon'
make[1]: *** [CMakeFiles/Makefile2:20167: ufo/test/CMakeFiles/test_ObsOperatorTLAD.x.dir/all] Error 2
make[1]: Leaving directory '/home/arango/ocean/repository/git/roms-jedi/build_latlon'
```

Is it possible that I am missing an update? I am using **`feature/replace_geometry_latlon`** in OOPS and SABER, but I didn't find one for UFO.

**Comment by fmahebert** [comment]
@hga007 I think that's because a PR was just merged in OOPS that changes the interface with UFO, unrelated to my PR removing the `latlon` method from the Geometry, but made my branches get out-of-date. I've just updated my PR branches in OOPS and SABER, so hopefully it will compile for you now.

**Review by guillaumevernieres — APPROVED** [review]
:+1: 
I'll just need to remind myself to update the gdasapp. Looks like I'm making use of latlon.

**Comment by hga007** [comment]
@fmahebert:  Okay, it compiles and runs successfully now. Thank you!

**Comment by travissluka** [comment]
> 👍 I'll just need to remind myself to update the gdasapp. Looks like I'm making use of latlon.

@guillaumevernieres  Let me know when you have changes ready on your end, I'll keep this PR open in the meantime.

**Comment by shlyaeva** [comment]
upstream branches were merged; this can be merged too.

**Comment by travissluka** [comment]
> upstream branches were merged; this can be merged too.

not yet, waiting on @guillaumevernieres

**Pull request merged**
