### PR TITLE
Use VADER for hofx3d test

### LINKED ISSUE #924: Replace `InsituTemperature` ufo operator with the generic vert interp (for non-linear)
## Description
Use VADER to do the insitu/potential temperature conversion. Once that capability is added to VADER (in a separate issue) change the SOCA yaml files to use the generic vertical interpolator UFO and make sure the conversion in VADER is working as intended.

* [x] change the soca ctests to use VADER/generic-vert-interp
* [x] Compare the two methods (variable conversion in VADER vs in UFO) and make sure they are roughly equivalent.
* [ ] ~~create PRs for similar changes in Skylab and soca-science~~ (will do this after linear variable change is added)

### PR DESCRIPTION
**Pull request by travissluka**
## Description

- closes https://github.com/JCSDA-internal/soca/issues/924

- a temporary "hack" so that the variables needed by VADER are renamed before VADER is called. (eventually this will go away when state variables are renamed throughout the SOCA code)
- add latitude and longitude to the possible state variables that VADER can use
- hofx3d now uses just a plain `VertInterp` for the T/S profiles.

## dependencies
- requires https://github.com/JCSDA-internal/vader/pull/189
- requires the ctests answers to be updated here once the VADER PR is finalized.

### CODE REVIEW

**Comment by Dooruk** [comment]
I think it hofx should work now with the latest VADER changes but I'm still receiving the following error. I pulled the changes regarding in terms of fieldnames and obsop files:

```
55: FieldSet: cannot find field "sea_water_temperature" caught in  (~/vader_dev/oops/src/oops/runs/Run.cc +193 execute)
55: Exception: oops::HofX3D<SOCA, UFO and IODA observations> terminating...
55: Exception stack: 
55: FieldSet: cannot find field "sea_water_temperature"
55: backtrace [1] stack has 16 addresses
55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/eckit-1.23.0-oify5by/lib64/libeckit.so+eckit::BackTrace::dump[abi:cxx11]())0x1b0 
55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/eckit-1.23.0-oify5by/lib64/libeckit.so+eckit::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, eckit::CodeLocation const&))0x190 
55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/ecmwf-atlas-0.33.0-wpyr34n/lib64/libatlas.so.0.33+atlas::throw_Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, eckit::CodeLocation const&))0x25 
55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/ecmwf-atlas-0.33.0-wpyr34n/lib64/libatlas.so.0.33+atlas::field::FieldSetImpl::field(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<FieldSet: cannot find field "sea_water_temperature" caught in  (/discover/nobackup/dardag/JediSODA/vader_dev/oops/src/oops/runs/Run.cc +193 execute)
55: Exception: oops::HofX3D<SOCA, UFO and IODA observations> terminating...
55: Exception stack: 
55: FieldSet: cannot find field "sea_water_temperature"
55: backtrace [1] stack has 16 addresses
```

**Comment by travissluka** [comment]
> I think it hofx should work now with the latest VADER changes but I'm still receiving the following error. I pulled the changes regarding in terms of fieldnames and obsop files:
> 
> ```
> 55: FieldSet: cannot find field "sea_water_temperature" caught in  (~/vader_dev/oops/src/oops/runs/Run.cc +193 execute)
> 55: Exception: oops::HofX3D<SOCA, UFO and IODA observations> terminating...
> 55: Exception stack: 
> 55: FieldSet: cannot find field "sea_water_temperature"
> 55: backtrace [1] stack has 16 addresses
> 55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/eckit-1.23.0-oify5by/lib64/libeckit.so+eckit::BackTrace::dump[abi:cxx11]())0x1b0 
> 55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/eckit-1.23.0-oify5by/lib64/libeckit.so+eckit::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, eckit::CodeLocation const&))0x190 
> 55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/ecmwf-atlas-0.33.0-wpyr34n/lib64/libatlas.so.0.33+atlas::throw_Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, eckit::CodeLocation const&))0x25 
> 55: (/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/install/intel/2022.0.1/ecmwf-atlas-0.33.0-wpyr34n/lib64/libatlas.so.0.33+atlas::field::FieldSetImpl::field(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<FieldSet: cannot find field "sea_water_temperature" caught in  (/discover/nobackup/dardag/JediSODA/vader_dev/oops/src/oops/runs/Run.cc +193 execute)
> 55: Exception: oops::HofX3D<SOCA, UFO and IODA observations> terminating...
> 55: Exception stack: 
> 55: FieldSet: cannot find field "sea_water_temperature"
> 55: backtrace [1] stack has 16 addresses
> ```

hmm, @Dooruk indeed. It's not working for me either. Though it was on Friday, I'll look into it

**Comment by travissluka** [comment]
@Dooruk with the bug fixes I pointed out in the vader pr, we now get a difference of answers in the hofx test of 
```
55: Test Val : 7.7988570164766813e+00
55: Ref  Val : 7.7995978223639364e+00
55: Delta    : 7.4080588725511376e-04
```
which is small enough for me, seems to be working! :tada:

**Review by Dooruk — APPROVED** [review]
Awesome, I'm getting an even smaller error 😄  

```
Delta    : 6.1395693908483651e-04
```

**Pull request merged**
