### PR TITLE
Remove old static B code

### LINKED ISSUE #973: Remove old / unused static B stuff
Once the EXPLICIT_DIFFUSION operator is done, delete the following:

- soca custom error covariance class (use BUMP_NICAS or EXPLICIT_DIFFUSION)
- `HorizFilt` - this is not normalized and shouldn't be used anyway
- `VertConv` - this also is not normalized and should not be used anyway

### PR DESCRIPTION
**Pull request by travissluka**
## Description

Removes `VertConv` , `HorizFilt,` and `SocaError`, as these have been replaced by `EXPLICIT_DIFFUSION` saber central block.

- closes #973 

### What was changed

- Delete the `VertConv` class and remove from ctests
- Delete the `HorizFilt` class and remove from ctests
- Mostly delete the `SocaError` class (empty stubs are still needed for `traits.h`) and replace with `EXPLICIT_DIFFUSION` in the ctests
- Implement randomization for `EXPLICIT_DIFFUSION` (multiplying gaussian noise by the square root of the diffusion operator), for the `enspert` test
- generic clean up of the ctests
  - some ctests were renamed. Now it is assumed that, unless noted otherwise in the test name, a ctest uses `EXPLICIT_DIFFUSION` for correlation and `BUMP_NICAS` for localization.
  - a `data_output/` directory is created for each ctest working directory to put its output. This way, I can easily grep the `testinput/` config files to see what the inputs for a ctest are `./data_generated/...`

### CODE REVIEW

**Comment by travissluka** [comment]
over 3,000 lines of code deleted, woo :tada:

**Review by guillaumevernieres — APPROVED** [review]
:bomb:

**Review by kbhargava — APPROVED** [review]
🔥

**Comment by travissluka** [comment]
GPT: "A JEDI computer programmer about to delete thousands of lines of code. Sitting at his computer, laughing, surrounded by an apocalyptic ocean and sea-ice scene outside"
image

**Pull request merged**
