### PR TITLE
adapt to changes in VariableChange in oops

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Adaptation to https://github.com/JCSDA-internal/oops/pull/1008

## Testing

I only built it 😞  and I'm hoping for Travis CI. (tests for soca don't pass on my machine, and I didn't have patience to figure it out).

## Dependencies

- waiting on https://github.com/JCSDA-internal/oops/pull/1008

### CODE REVIEW

**Comment by shlyaeva** [comment]
Looks like `3dvarlowres_soca` is failing on compare:
> Float mismatch at line 11: 34.574733  not equal to  34.574734  with max relative difference  1e-12  Actual relative difference =  2.8922854402155133e-08
Float mismatch at line 13: 0.841025  not equal to  0.841026  with max relative difference  1e-12  Actual relative difference =  1.1890238827678997e-06
Float mismatch at line 17: 73279.901046  not equal to  73313.361550  with max relative difference  1e-12  Actual relative difference =  0.00045661229780511885
Float mismatch at line 18: 405.366241  not equal to  405.366143  with max relative difference  1e-12  Actual relative difference =  2.4175668772129145e-07
Float mismatch at line 19: 49.365034  not equal to  49.365035  with max relative difference  1e-12  Actual relative difference =  2.025725288101675e-08
Float mismatch at line 20: 85.214111  not equal to  85.214141  with max relative difference  1e-12  Actual relative difference =  3.520543638982186e-07
Float mismatch at line 21: 4469.367791  not equal to  4469.368671  with max relative difference  1e-12  Actual relative difference =  1.9689585674328806e-07
Float mismatch at line 21: 21.695960  not equal to  21.695964  with max relative difference  1e-12  Actual relative difference =  1.843661131470098e-07
Float mismatch at line 22: 361.728535  not equal to  361.728571  with max relative difference  1e-12  Actual relative difference =  9.95221454299424e-08
Float mismatch at line 23: 78650.942759  not equal to  78684.404111  with max relative difference  1e-12  Actual relative difference =  0.00042544120675201995

Not sure what could cause it to fail in this PR; is this by any chance a known issue with develop? @guillaumevernieres, @travissluka

**Comment by shlyaeva** [comment]
Looks like it is, since develop build is failing.

**Review by guillaumevernieres — APPROVED** [review]
Thanks @shlyaeva

**Comment by shlyaeva** [comment]
oops PR was merged; this PR can be merged now too.

**Pull request merged**
