### PR TITLE
disable git lfs for saber

### PR DESCRIPTION
**Pull request by mer-a-o**

### CODE REVIEW

**Comment by travissluka** [comment]
@mer-a-o `git lfs install --skip-smudge` might do the trick, instead of `git lfs uninstall`

**Comment by aerorahul** [comment]
@mer-a-o 
Also, 
`export GIT_LFS_SKIP_SMUDGE=1`
before a `git clone` also skips downloading lfs files.

To re-enable
`export GIT_LFS_SKIP_SMUDGE=0`

**Comment by travissluka** [comment]
it turns out soca tests dont depend on binary files from any other repo. So we should be able to skip the lfs for all non-soca jedi repos (oops/crtm/ioda/ioda-converters/ufo)
Should be a big speedup!

**Comment by mer-a-o** [comment]
Thanks @travissluka and @aerorahul ! Looks like it worked. Can we disable git lfs for any other repo in soca-bundle?

**Comment by travissluka** [comment]
awesome :+1: That should help out quite a bit with the git-lfs bandwidth issues if done to all the other projects.

**Comment by mer-a-o** [comment]
@travissluka: good idea. This PR is ready to merge then.

**Review by travissluka — APPROVED** [review]

**Review by aerorahul — APPROVED** [review]
not sure how to test this, but they look right.

**Pull request merged**
