### PR TITLE
Feature/godas d

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Implementation of GODAS D. No comments on the norms please! Fixed in a different branch.

### CODE REVIEW

**Review by travissluka — CHANGES_REQUESTED** [review]
file ./Utils/soca_omb_stats_mod.F90 is missing from repo

**Comment by guillaumevernieres** [comment]
oops, sorry. Just pushed.

**Comment by travissluka** [comment]
I'm seeing a weird pattern in the bkg error along a single stripe (look at cold tongue below the surface) when running **test_soca_3dvar**. It looks fine after **test_soca_bkgerr** though
 
bkgerr

**Comment by guillaumevernieres** [comment]
Thanks for catching that @travissluka . I also see that the bkg error changes with the number of cpu's ... Interesting feature, but maybe not what we want! I'm looking into it.

**Comment by travissluka** [comment]
that pattern is gone, but I'm seeing a difference between the **test_soca_bkgerr** (left) and 
**test_soca_3dvar** (right) @guillaumevernieres  is it supposed to be that way?
image

**Review by travissluka — APPROVED** [review]
seems to work now.

**Pull request merged**
