### PR TITLE
Use original background for shuffling in Soca2Cice

### LINKED ISSUE #1103: Improve Soca2Cice shuffling
## Description

The shuffle option in Soca2Cice currently is changing data in place. It means that during the loop through the data we lose info on some of the original cice fields that could have been useful for shuffling.

## Solution
Fix by having a copy of the background to refer to when shuffling.

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

The shuffle option in Soca2Cice on develop is changing data in place. It means that during the loop through the data we lose info on some of the original cice fields that could have been useful for shuffling; @guillaumevernieres reported that he saw large areas of identical sea ice state when using shuffle.

This PR changes the shuffle option to use the original background. See some results in https://github.com/JCSDA-internal/soca/issues/1103.

It also sneaks in a missed change that was required for the Parameters merge.

### Issue(s) addressed

Fixes https://github.com/JCSDA-internal/soca/issues/1103

## Testing

orion with gnu, soca ctests
hera with intel, high res gfsv17 experiment (see some plots in https://github.com/JCSDA-internal/soca/issues/1103)

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Review by Dooruk — APPROVED** [review]

**Comment by shlyaeva** [comment]
Thank you all for the quick reviews and merge, this is close to my personal record between opening PR and having it merged :)

**Comment by shlyaeva** [comment]
(especially among the PRs I didn't merge myself 😆 )

**Comment by Dooruk** [comment]
> Thank you all for the quick reviews and merge, this is close to my personal record between opening PR and having it merged :)

Well, you already have the YOLO badge :)

**Pull request merged**
