### PR TITLE
Replace {{workdir}} template before reaching run time

### PR DESCRIPTION
**Pull request by cmgas**
Companion PR for 
- JCSDA-internal/ewok/pull/347
- JCSDA-internal/oops/pull/1831
- JCSDA-internal/fv3-jedi/pull/549

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
I tried hard to find errors/mixups in this PR and the companion PRs, but I didn't.

**Review by ytremolet — APPROVED** [review]
Ran the 5 deg experiment.

**Comment by guillaumevernieres** [comment]
> Ran the 5 deg experiment.

@ytremolet has finally achieved greatness! :tada:

**Comment by ytremolet** [comment]
ewok and oops PRs merged. Let me know if you want me to merge this one or wait for the Travises.

**Pull request merged**
