### PR TITLE
remove travisci related scripts

### LINKED ISSUE #1029: Remove TravisCI
I think we're ready to retire TravisCI. As far as I know, it was only being used for soca, and soca-science.

- [x] remove the TravisCI hooks from the JCSDA github: @eap @climbfuji  (I don't have the permissions any more to do this)
- [x] issue PR to remove the code from the soca repo that was being used for travisCI  (@travissluka )

### PR DESCRIPTION
**Pull request by travissluka**
## Description
- closes https://github.com/JCSDA-internal/soca/issues/1029

TravisCI has been disabled since we are using the new CI reliably now. This removes the scripts that had been used for TravisCI.

Goodbye other Travis.

### CODE REVIEW

**Comment by travissluka** [comment]
thanks @climbfuji , I confirm that the TravisCI check no longer shows in PRs

**Review by climbfuji — APPROVED** [review]
1 .. 2 .. 3 .. gone!

**Comment by travissluka** [comment]
ignore the integration test failure, unrelated to this.

**Review by kbhargava — APPROVED** [review]
Nice branch name. I haven;t tested but don;t think this should impact any of our work.

**Pull request merged**
