### PR TITLE
Adapt to saber block interface change

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Adapt to change in https://github.com/JCSDA-internal/saber/pull/727

build-group=https://github.com/JCSDA-internal/oops/pull/2454
build-group=https://github.com/JCSDA-internal/saber/pull/727

### CODE REVIEW

**Review by travissluka — APPROVED** [review]

**Review by kbhargava — COMMENTED** [review]
Looks good but build fails again on orion. Might be due to the corresponding saber branch being out of date with the base branch.

**Comment by shlyaeva** [comment]
I've just updated the saber branch, that might help!

**Comment by shlyaeva** [comment]
oops and saber PRs were merged, this can be merged now too

**Comment by travissluka** [comment]
@kbhargava , or anyone, can you please review so I can merge. I no longer have admin privileges on SOCA so I can't merge unless there's 2 reviews

**Review by ytremolet — APPROVED** [review]

**Pull request merged**
