### PR TITLE
use oops_variables 

### LINKED ISSUE #258: Use "oops_variable" in the Fortran code
## Description
The Variables class was updated in oops to include a new shiny Fortran interface. We need to use that instead of the current `&vars.toFortran();` that we're currently using before they rip that part out. (see the oops issue for details)

## Related to
- needed by JCSDA/oops/issues/337

### PR DESCRIPTION
**Pull request by travissluka**
## Description

This PR uses the fortran interface that was recently added to `oops::Variables` 
- all instances of `oops_vars` in the soca Fortran code have been replaced by `oops_variables`
- some minor syntax changes to accommodate that
- interface code updated to handle how `oops_variables` is created

These changes are needed so that JCSDA/oops/issues/337 can continue.

### Issue(s) addressed
- fixes JCSDA/soca/issues/258

## Testing

- Tested with GCC7.4 and Intel19
- no change in answers

### CODE REVIEW

**Comment by travissluka** [comment]
@mmiesch It turns out everything is okay now, The problem I was complaining about earlier today was a bug on my part.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by mmiesch** [comment]
Thanks @travissluka - I have a branch in oops that has the changes I mentioned - I'm just running some tests now - I'l do a PR very soon.

**Comment by travissluka** [comment]
@frolovsa This makes a small change to how variable names are passed between C and Fortran. I don't think this impacts your GeometryIterator work, but thought I would warn you just in case.

**Pull request merged**
