### PR TITLE
File clean-up

### PR DESCRIPTION
**Pull request by guillaumevernieres**
Removal of unused files. I kept the "exp" directory intact thinking this is where @travissluka would put cycling tests, happy to remove it if not.

### CODE REVIEW

**Comment by travissluka** [comment]
@guillaumevernieres can you go through the `testinput/unused` directory as well and remove anything that you don't think we'll be reviving in the future? I'd say rip out the `exp` directory as well, so long as no one else is using those scripts for anything currently.

**Comment by guillaumevernieres** [comment]
... just went through a file hoarding 12 step program.

**Comment by travissluka** [comment]
@guillaumevernieres great, step 13 is taking a look at the stale soca branches ;)

**Comment by guillaumevernieres** [comment]
@travissluka nope, totally different program, 12 steps required as well.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
