### PR TITLE
Feature/release/soca 1.0.0/cleaning

### LINKED ISSUE #497: lat/lon on the ice restart file are wrong, making it look like we have Sub-Saharan and Mediterranean ice.
Not that it matters, but I thought it was funny that the lat/lon on the ice restart file are wrong, making it look like we have Sub-Saharan and Mediterranean ice.
image

_Originally posted by @travissluka in https://github.com/JCSDA-internal/soca/issues/495#issuecomment-734987805_

### LINKED ISSUE #646: Clean up
- Point to the MOM6 release branch in teh bundle CMakeLists.txt
- Remove the rtd

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
Minor cleanup:
- removed of the rtd
- removed lonq, latq in cice.res.nc 
- pointing to the release branch of MOM6 in the bundle 

### Issue(s) addressed
- fixes #497 
- fixes #646

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Not sure what that file is used for: `testinput/marine2ioda.yml` @travissluka ?

**Comment by travissluka** [comment]
> Not sure what that file is used for: `testinput/marine2ioda.yml` @travissluka ?

I think its leftover from back when ioda-converter was test as part of soca. Delete it.

**Comment by guillaumevernieres** [comment]
@travissluka looks like I forgot to add travis-ci for the release/soca-1.0.0
Is that where the branch needs to be added? https://github.com/JCSDA-internal/soca/blob/5a1b2ab45dc15c7da5d1170a9c1ca95aab724219/.travis.yml#L34

**Comment by travissluka** [comment]
> @travissluka looks like I forgot to add travis-ci for the release/soca-1.0.0 Is that where the branch needs to be added?
> 
> https://github.com/JCSDA-internal/soca/blob/5a1b2ab45dc15c7da5d1170a9c1ca95aab724219/.travis.yml#L34

yep

**Review by travissluka — APPROVED** [review]

**Pull request merged**
