### PR TITLE
Turn off VertConv for ocean BGC

### LINKED ISSUE #590: VertConv for ocean BGC
## Description
Doing vertical convolution for ocean BGC seems to routinely cause solver issues (e.g. producing NaN after a few iterations). This problematic behavior is, however, not consistent when soca is built with GNU vs. Intel.

A temporal fix would be to simply turn `VertConv` off for ocean BGC and do it in BGC checkpoint applications. e.g. apply 2D surface analysis in 3D based on vertical distributions, but we need to revisit this issue to fundamentally solve the problem.

### PR DESCRIPTION
**Pull request by liuxiao37k**
## Description

Turn off VertConv for ocean BGC. See #590 for issue description. This PR, however, does not fundamentally solve the described problem but rather provide a temporal solution to get pass soca-science ctests.

# Tests
soca-science 3dvar_bgc ctest failed travis-ci with VertConv on (built with soca develop branch):
[build link](https://travis-ci.com/github/JCSDA-internal/soca-science/builds/228749985)
and passed with VertConv off (built with this branch):
[build link](https://travis-ci.com/github/JCSDA-internal/soca-science/builds/228753937)

### CODE REVIEW

**Comment by liuxiao37k** [comment]
@guillaumevernieres Sorry, another quick PR seems to be needed to address the NaN issue... with this update I can finally pass travis-ci.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Sorry, another quick PR seems to be needed to address the NaN issue... with this update I can finally pass travis-ci.

@liuxiao37k , you are the master of your domain, so I'll approve if that's what you really want to do, but could you create a "bug" issue so we remember to fix this in the future?

**Comment by liuxiao37k** [comment]
> > @guillaumevernieres Sorry, another quick PR seems to be needed to address the NaN issue... with this update I can finally pass travis-ci.
> 
> @liuxiao37k , you are the master of your domain, so I'll approve if that's what you really want to do, but could you create a "bug" issue so we remember to fix this in the future?

@guillaumevernieres good suggestion. I edited issue #590 to further describe the problem (i.e. doing vertconv for BGC routinely creates NaN with GNU, but not with Intel, and I have been testing with different data and filters which didn't really help), and made a note that this PR only provides a temporal fix to pass ctests. I would definitely want to revisit this issue later. thanks!

**Comment by liuxiao37k** [comment]
@guillaumevernieres and perhaps those hardwired variables would be eventually moved out of the source code so that we can control in .yaml which variables we want to do vertconv with?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres and perhaps those hardwired variables would be eventually moved out of the source code so that we can control in .yaml which variables we want to do vertconv with?

@liuxiao37k  If you are using "SocaError" as your covariance model, it is only 2D, so all 3D variable would require `VertConv` to make it 3D. Your var is going to be wrong without fixing that bug. We're not using BGC yet, so I'm open to making the test wrong, but considering that you've cornered the bug down to VertConv, why not just fix it? Is your issue not being able to replicate the bug on Hera or Orion?

To answer your question: Yes, at some point will will revamp our change of variables to make the input/output variables choice more flexible.

**Comment by liuxiao37k** [comment]
> > @guillaumevernieres and perhaps those hardwired variables would be eventually moved out of the source code so that we can control in .yaml which variables we want to do vertconv with?
> 
> @liuxiao37k If you are using "SocaError" as your covariance model, it is only 2D, so all 3D variable would require `VertConv` to make it 3D. Your var is going to be wrong without fixing that bug. We're not using BGC yet, so I'm open to making the test wrong, but considering that you've cornered the bug down to VertConv, why not just fix it? Is your issue not being able to replicate the bug on Hera or Orion?
> 
> To answer your question: Yes, at some point will will revamp our change of variables to make the input/output variables choice more flexible.

Oh sure, it would be great if we can actually fix the issue (although for BGC only 2D surface analysis is taken and the 3D field analysis will be generated based on 2D analysis as well as background vertical distributions in .py scripts). My issue is that I don't know how to fix it, so any help is appreciated.
See the travis-ci tests with `VertConv` on ([link](https://travis-ci.com/github/JCSDA-internal/soca-science/builds/228749985)):
```
RPCG Starting Iteration 1
5712RPCG alpha = 0.308053
5713RPCG end of iteration 1
5714  Gradient reduction ( 1) = 8.580603313088303e+116
5715  Norm reduction ( 1) = 4.992094945483949e+115
5716
5717RPCG Starting Iteration 2
5718RPCG beta = 2492101194472639760087050174335677991176518254049227003286194533401360503603853900768268093544002868597683434253837222602388600014375149021378707176141394844113498325795685241184060631142095127104574060169490256621299025338370621440.000000
5719RPCG alpha = -nan
5720RPCG end of iteration 2
5721  Gradient reduction ( 2) = -nan
5722  Norm reduction ( 2) = -nan
```
and with `VertConv` off ([link](https://travis-ci.com/github/JCSDA-internal/soca-science/builds/228753937))
I cannot replicate this issue on Hera (haven't figured out an GNU option) and having login issue on Orion, but with Hera Intel I encountered similar NaN problems many times with the 1deg tests.

**Comment by liuxiao37k** [comment]
Hi @guillaumevernieres, as we discussed last week, ocean BGC DA is done at a 2D space so it does not make a lot sense to do `VertConv`, so we decided to proceed with this PR. Before you merge, can you please check again what I have done (long time ago) with `GetValues` to make sure that I did not mess up the BGC states' dimensions? thank you!

**Review by guillaumevernieres — APPROVED** [review]
That's fine for now @liuxiao37k , but this is definitely a bug. I understand you just want to do a 2D analysis, but this is not how it should be done. You are carrying around a 3D state for no reason (not really your fault). We'll revisit your issue when we cleanup our change of variables ... "soon".

**Comment by liuxiao37k2** [comment]
@guillaumevernieres thanks and I fully understand your point. I'll keep it in mind that we should revisit this issue.

**Comment by liuxiao37k** [comment]
@guillaumevernieres never mind what @liuxiao37k2 said. It was me forgetting to switch account. hmmm... I thought soca was a private repository...

**Pull request merged**
