### PR TITLE
Add a simple chlorophyll 3DVAR ctest

### LINKED ISSUE #432: Add a simple chlorophyll 3DVAR ctest
## Description
Include chlorophyll in the SOCA 3DVAR ctest. Due to a number of issues yet to be resolved (e.g. geovals refactoring, log-transformation, depth integration and penetration), here we start simple by only assimilating surface chlorophyll using the `Identity` operator. This feature will be revisited and improved at a later stage to integrate cutting-edge science.

## Solution
The proposed solution is implemented in a feature branch [here](https://github.com/JCSDA/soca/tree/feature/chl_3dvar).

`ocn.bkgerror.nc` is updated to include `chl`, the values of which are set to be 30% of the background values according to literature.

### PR DESCRIPTION
**Pull request by liuxiao37k**
## Description

To include chlorophyll in the SOCA 3DVAR ctest. Due to issues yet to be resolved (e.g. geovals refactoring, log-transformation, depth integration and penetration), here we start simple by only assimilating surface chlorophyll using the `Identity` operator. This added feature will be revisited and improved at a later stage to integrate cutting-edge science.

### Issue(s) addressed
- fixes #432 

## Testing
These updates were tested on Hera.

### CODE REVIEW

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
- It doesn't look like the obs file you added is handled by git-lfs, please remove it and add it with lfs.
- Build in debug mode to recreate the test failure, looks like you have a bug somewhere.

**Comment by liuxiao37k** [comment]
> * It doesn't look like the obs file you added is handled by git-lfs, please remove it and add it with lfs.
> * Build in debug mode to recreate the test failure, looks like you have a bug somewhere.

Thank you, @guillaumevernieres: 1) Obs file has been restored (no need to change); 2) Let me check on the failed Travis test; it's odd because it passed Hera. I'll let you know after I figure out and fix the problem, or if I need help. Thanks!!

**Comment by guillaumevernieres** [comment]
> > * It doesn't look like the obs file you added is handled by git-lfs, please remove it and add it with lfs.
> > * Build in debug mode to recreate the test failure, looks like you have a bug somewhere.
> 
> Thank you, @guillaumevernieres: 1) Obs file has been restored (no need to change); 2) Let me check on the failed Travis test; it's odd because it passed Hera. I'll let you know after I figure out and fix the problem, or if I need help. Thanks!!

I actually built your branch locally, the test is OK in release build, but the increment doesn't look right at all. You should see a failure in debug build with a nice traceback to the problem.

**Comment by guillaumevernieres** [comment]
@liuxiao37k , looks like this is ready for review/merging? I'll let you "un-draft" it.

**Comment by liuxiao37k** [comment]
@jkbk2004 such that you get notifications :)

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
Nice! But not quite done yet. The chl increment is only at the surface, you need to add chl to the vertical convolution as well.
Just add "chl" in the case statements [here (forward)](https://github.com/JCSDA/soca/blob/4e9688de58e28d0926a809d6f577a4d32165c0dd/src/soca/Transforms/VertConv/soca_vertconv_mod.F90#L118) and [here (adjoint)](https://github.com/JCSDA/soca/blob/4e9688de58e28d0926a809d6f577a4d32165c0dd/src/soca/Transforms/VertConv/soca_vertconv_mod.F90#L167)
The rest looks good.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Pull request merged**
