### PR TITLE
Remove EnsVariance application and test (EnsMeanAndVariance supersedes it)

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Adaptation to https://github.com/JCSDA-internal/oops/pull/2394: removing `EnsVariance` application and test. `EnsMeanAndVariance` application that is already used in soca can do everything `EnsVariance` could do and more. 

I have removed the `ensvariance` test, because it is using the same input files as `ensmeanandvariance` test to compute and output ensemble variance. I checked that variance files produced by `ensvariance` and `ensmeanandvariance` tests are very similar (biggest difference is order of 10^-16, I think that's reasonable). Removing `ensvariance` test doesn't affect functionality coverage, since `ensmeanandvariance` test covers the functionality + more.

## Testing

aws single node; spack-stack/1.5.0

## Dependencies

build-group=https://github.com/JCSDA-internal/oops/pull/2394
build-group=https://github.com/JCSDA-internal/fv3-jedi/pull/1062

### CODE REVIEW

**Comment by shlyaeva** [comment]
@kbhargava, @guillaumevernieres: this is needed for the merge of https://github.com/JCSDA-internal/oops/pull/2394 which was scheduled for two days ago :) but was delayed to let all the model interfaces to adapt (see https://github.com/orgs/JCSDA-internal/discussions/81)
If you can review today and confirm that removal of `EnsVariance` application is OK for the applications outside of tests, that would be great (note: you can use `EnsMeanAndVariance` application to do the same as `EnsVariance`; see example in soca tests).

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Review by kbhargava — APPROVED** [review]
Looks good to me. Thanks @shlyaeva. I will have to make some minor changes to soca-science. Updating that soon.

**Comment by svahl991** [comment]
Upstream OOPS PR is now merged, so this PR can and should now merge also.

**Comment by guillaumevernieres** [comment]
> Upstream OOPS PR is now merged, so this PR can and should now merge also.

@svahl991 , @shlyaeva I don't have merging "powers" anymore, and I think @travissluka is on leave. Could one of  you "click" merge?

**Comment by shlyaeva** [comment]
Me neither :) Pinging @kbhargava, @ytremolet, @climbfuji if they can merge.

**Pull request merged**
