### PR TITLE
doxygen documentation and cleanup

### PR DESCRIPTION
**Pull request by travissluka**
## Description

touch pretty much every single source code file in soca...

- update copyright dates to `-2021`
- document all of the fortran code with doxygen
- general cleanup of the fortran code to make things more consistent (class structures, indentation, etc.)
- remove all `use ...` statements for modules that were never used
- ...other things i'm probably forgetting

## Testing

since TravisCI is not happy these days, manually ran ctests on my own machine

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@travissluka , looks like you started your feature branch from develop, not the release branch? I don't think the ufo fix was part of the release branch ... Build's failing.

**Comment by travissluka** [comment]
@guillaumevernieres yes, but I realized my mistake, rebased off of the release branch, and undid the ufo change.
It should build fine. We're seeing that pesky travisci issue again
```
{standard input}: Assembler messages:
{standard input}: Fatal error: bfd_make_empty_symbol: memory exhausted
{standard input}: Fatal error: can't close CMakeFiles/soca_hofx3d.x.dir/HofX3D.cc.o: memory exhausted
make[2]: *** [src/mains/CMakeFiles/soca_hofx3d.x.dir/build.make:76: src/mains/CMakeFiles/soca_hofx3d.x.dir/HofX3D.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1560: src/mains/CMakeFiles/soca_hofx3d.x.dir/all] Error 2
```

**Review by guillaumevernieres — APPROVED** [review]
Thanks @travissluka , looks nice! I got a kick out of looking at some of the diagrams, a few of them are too wide to fit within whatever doxygen has for max width ... Oops. 
I checked every single changes, 100% all good.

**Comment by guillaumevernieres** [comment]
Ho, and look at you showing off with 0.27% increase in coverage! Noice.

**Pull request merged**
