### PR TITLE
Modified the 3dvar_soca_yml file to apply the QC filters for SST, SSS…

### PR DESCRIPTION
**Pull request by ShastriPaturi**
The 3davar_soca.yml has been modified to apply the QC filters across all the datasets.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
At first glance:
1. It seems that you forgot to add the obsfile
2. We want to keep the files small, could you make sure your obsfiles are of comparable size to the current one. If not, sub-sample!

**Comment by aerorahul** [comment]
@ShastriPaturi Is there a reason why `CoolSkin` is being removed from the test?
Also, do these new observation files contain information that was not present in the ones currently in the Git-LFS repository?

**Comment by ShastriPaturi** [comment]
> @ShastriPaturi Is there a reason why `CoolSkin` is being removed from the test?
@aerorahul, I did not test 'CoolSkin'. 
> Also, do these new observation files contain information that was not present in the ones currently in the Git-LFS repository?
@aerorahul, TRACKOB (trak in the yaml file) data has sea surface temperature and salinity collected along a ship's track using Thermosalinographs (TSG).  These data are in NCEP data tanks in BUFR format and in binary format from FNMOC.

**Comment by ShastriPaturi** [comment]
> > @ShastriPaturi Is there a reason why `CoolSkin` is being removed from the test?
> > @aerorahul, I did not test 'CoolSkin'.
> > Also, do these new observation files contain information that was not present in the ones currently in the Git-LFS repository?
> > @aerorahul, TRACKOB (trak in the yaml file) data has sea surface temperature and salinity collected along a ship's track using Thermosalinographs (TSG).  These data are in NCEP data tanks in BUFR format and in binary format from FNMOC.


    @ShastriPaturi Is there a reason why CoolSkin is being removed from the test?
    @aerorahul, I did not test 'CoolSkin'.
    Also, do these new observation files contain information that was not present in the ones currently in the Git-LFS repository?
    @aerorahul, TRACKOB (trak in the yaml file) data has sea surface temperature and salinity collected along a ship's track using Thermosalinographs (TSG). These data are in NCEP data tanks in BUFR format and in binary format from FNMOC.
Source: https://www.jcomm.info/index.php?option=com_content&view=article&id=15&Itemid=0

**Comment by flampouris** [comment]
@ShastriPaturi 
The list of the available filters has been updated since the code sprint in March, so some additional filters have to be tested for the ocean obs.  The list of the filters could be retrieved from the factory (instantiateObsFilterFactory.h) at source code of soca, which points to the actual code of the filters at UFO, check it for getting the details of each filter.
Maybe,  you could retrieve some examples of filter application from the tests of the atmospheric models.

Let's close for now the PR, but you can reopen it whenever you are ready.

**Pull request closed without merging**
