### PR TITLE
Cumulative bug fixes

### PR DESCRIPTION
**Pull request by travissluka**
## Description

This fixes several bugs that were causing problems, mainly with intel compilers.

1. When compiling in debug mode the following error popped up, It turns out I was trying to copy a 3D array to a 2D array (ssh in this case). I can only imagine what intermittent undetected damage was being done to memory. Thanks @climbfuji  for finding the bug.
```
48: At line 623 of file /home/tsluka/work/soca/bundle/soca/src/soca/ExplicitDiffusion/soca_diffusion.F90
48: Fortran runtime error: Array bound mismatch for dimension 3 of array 'params' (25/1)
```
2. on intel compilers I was getting a weird divide by zero error in Diffusion. I put in an `if` statement that _should_ do nothing, and for some reason the error goes away. :man_shrugging:  I'm moving on from this one for now, hopefully we'll switch to the generic diffusion code soon enough.
3. The mom6 ctest forecast run scripts were not working under intel because `mom6.x` was called directly and not under `mpirun`, this fixes that
4. the mom6 forecast now produces slightly different answers on orion/hercules intel. I'm not sure why, but since it's probably beyond my control I've just upped the tolerances for any ctest relying on the mom6 forecast.

@Dooruk and @climbfuji , I believe you had been seeing ctest failures on the machines you were testing on, this might fix that.

### CODE REVIEW

**Review by kbhargava — APPROVED** [review]
Thank you so much Travis!!! Ctests for soca on orion finally all pass with intel 🎉

**Comment by kbhargava** [comment]
I haven't tested with GNU but thought I'd paste the time taken by ctests with intel just in case you want an idea how slow/fast they go.
```
Test project /home/kritib/work2-jcsda/sandboxes/soca/build.intel/soca
      Start  1: soca_coding_norms
 1/57 Test  #1: soca_coding_norms ............................   Passed    4.19 sec
      Start  2: test_soca_gridgen
 2/57 Test  #2: test_soca_gridgen ............................   Passed   42.14 sec
      Start  3: test_soca_geometry
 3/57 Test  #3: test_soca_geometry ...........................   Passed    4.91 sec
      Start  4: test_soca_geometry_iterator_2d
 4/57 Test  #4: test_soca_geometry_iterator_2d ...............   Passed    4.50 sec
      Start  5: test_soca_state
 5/57 Test  #5: test_soca_state ..............................   Passed    6.32 sec
      Start  6: test_soca_increment
 6/57 Test  #6: test_soca_increment ..........................   Passed    4.53 sec
      Start  7: test_soca_modelaux
 7/57 Test  #7: test_soca_modelaux ...........................   Passed    4.18 sec
      Start  8: test_soca_getvalues
 8/57 Test  #8: test_soca_getvalues ..........................   Passed    6.56 sec
      Start  9: test_soca_varchange_ana2model
 9/57 Test  #9: test_soca_varchange_ana2model ................   Passed    4.40 sec
      Start 10: test_soca_varchange_balance
10/57 Test #10: test_soca_varchange_balance ..................   Passed    4.62 sec
      Start 11: test_soca_varchange_balance_TSSSH
11/57 Test #11: test_soca_varchange_balance_TSSSH ............   Passed    4.36 sec
      Start 12: test_soca_varchange_bkgerrfilt
12/57 Test #12: test_soca_varchange_bkgerrfilt ...............   Passed    4.22 sec
      Start 13: test_soca_varchange_bkgerrsoca
13/57 Test #13: test_soca_varchange_bkgerrsoca ...............   Passed    4.37 sec
      Start 14: test_soca_varchange_bkgerrsoca_stddev
14/57 Test #14: test_soca_varchange_bkgerrsoca_stddev ........   Passed    4.39 sec
      Start 15: test_soca_varchange_bkgerrgodas
15/57 Test #15: test_soca_varchange_bkgerrgodas ..............   Passed    6.68 sec
      Start 16: test_soca_obslocalization
16/57 Test #16: test_soca_obslocalization ....................   Passed    5.46 sec
      Start 17: test_soca_obslocalizations
17/57 Test #17: test_soca_obslocalizations ...................   Passed    4.31 sec
      Start 18: test_soca_forecast_identity
18/57 Test #18: test_soca_forecast_identity ..................   Passed    4.63 sec
      Start 19: test_soca_forecast_mom6
19/57 Test #19: test_soca_forecast_mom6 ......................   Passed   32.15 sec
      Start 20: test_soca_forecast_pseudo
20/57 Test #20: test_soca_forecast_pseudo ....................   Passed    5.15 sec
      Start 21: test_soca_forecast_mom6_ens1
21/57 Test #21: test_soca_forecast_mom6_ens1 .................   Passed   12.21 sec
      Start 22: test_soca_forecast_mom6_ens2
22/57 Test #22: test_soca_forecast_mom6_ens2 .................   Passed   13.78 sec
      Start 23: test_soca_forecast_mom6_ens3
23/57 Test #23: test_soca_forecast_mom6_ens3 .................   Passed   11.71 sec
      Start 24: test_soca_setcorscales
24/57 Test #24: test_soca_setcorscales .......................   Passed    4.26 sec
      Start 25: test_soca_parameters_bump_cor_nicas
25/57 Test #25: test_soca_parameters_bump_cor_nicas ..........   Passed    8.28 sec
      Start 26: test_soca_parameters_bump_cor_nicas_scales
26/57 Test #26: test_soca_parameters_bump_cor_nicas_scales ...   Passed   10.19 sec
      Start 27: test_soca_parameters_bump_loc
27/57 Test #27: test_soca_parameters_bump_loc ................   Passed    5.71 sec
      Start 28: test_soca_parameters_bump_cov
28/57 Test #28: test_soca_parameters_bump_cov ................   Passed   13.02 sec
      Start 29: test_soca_parameters_diffusion
29/57 Test #29: test_soca_parameters_diffusion ...............   Passed    8.98 sec
      Start 30: test_soca_enspert
30/57 Test #30: test_soca_enspert ............................   Passed    6.84 sec
      Start 31: test_soca_convertstate_changevar
31/57 Test #31: test_soca_convertstate_changevar .............   Passed    4.56 sec
      Start 32: test_soca_ensmeanandvariance
32/57 Test #32: test_soca_ensmeanandvariance .................   Passed    4.99 sec
      Start 33: test_soca_parametric_stddev
33/57 Test #33: test_soca_parametric_stddev ..................   Passed    6.41 sec
      Start 34: test_soca_ensrecenter
34/57 Test #34: test_soca_ensrecenter ........................   Passed    4.76 sec
      Start 35: test_soca_hybridgain
35/57 Test #35: test_soca_hybridgain .........................   Passed    4.94 sec
      Start 36: test_soca_sqrtvertloc
36/57 Test #36: test_soca_sqrtvertloc ........................   Passed   12.19 sec
      Start 37: test_soca_diffstates
37/57 Test #37: test_soca_diffstates .........................   Passed    4.40 sec
      Start 38: test_soca_dirac_soca_cor_nicas_scales
38/57 Test #38: test_soca_dirac_soca_cor_nicas_scales ........   Passed    4.56 sec
      Start 39: test_soca_dirac_soca_cov
39/57 Test #39: test_soca_dirac_soca_cov .....................   Passed    6.13 sec
      Start 40: test_soca_dirac_socahyb_cov
40/57 Test #40: test_soca_dirac_socahyb_cov ..................   Passed   10.50 sec
      Start 41: test_soca_dirac_diffusion
41/57 Test #41: test_soca_dirac_diffusion ....................   Passed    5.91 sec
      Start 42: test_soca_makeobs
42/57 Test #42: test_soca_makeobs ............................   Passed    5.58 sec
      Start 43: test_soca_hofx_3d
43/57 Test #43: test_soca_hofx_3d ............................   Passed    6.33 sec
      Start 44: test_soca_hofx_4d_pseudo
44/57 Test #44: test_soca_hofx_4d_pseudo .....................   Passed    4.96 sec
      Start 45: test_soca_3dvar
45/57 Test #45: test_soca_3dvar ..............................   Passed   12.12 sec
      Start 46: test_soca_3dvar_nicas
46/57 Test #46: test_soca_3dvar_nicas ........................   Passed    8.08 sec
      Start 47: test_soca_3dvarfgat_pseudo
47/57 Test #47: test_soca_3dvarfgat_pseudo ...................   Passed    9.67 sec
      Start 48: test_soca_3dhyb
48/57 Test #48: test_soca_3dhyb ..............................   Passed   13.26 sec
      Start 49: test_soca_3dhyb_diffusion
49/57 Test #49: test_soca_3dhyb_diffusion ....................   Passed   10.76 sec
      Start 50: test_soca_3dhybfgat_pseudo
50/57 Test #50: test_soca_3dhybfgat_pseudo ...................   Passed   11.27 sec
      Start 51: test_soca_4denvar
51/57 Test #51: test_soca_4denvar ............................   Passed    8.19 sec
      Start 52: test_soca_4dhybenvar
52/57 Test #52: test_soca_4dhybenvar .........................   Passed   11.15 sec
      Start 53: test_soca_letkf
53/57 Test #53: test_soca_letkf ..............................   Passed    6.75 sec
      Start 54: test_soca_letkf_split_observer
54/57 Test #54: test_soca_letkf_split_observer ...............   Passed    4.95 sec
      Start 55: test_soca_letkf_split_solver
55/57 Test #55: test_soca_letkf_split_solver .................   Passed    4.96 sec
      Start 56: test_soca_addincrement
56/57 Test #56: test_soca_addincrement .......................   Passed    4.31 sec
      Start 57: test_soca_convertincrement
57/57 Test #57: test_soca_convertincrement ...................   Passed    4.28 sec
```

**Comment by travissluka** [comment]
@kbhargava yeah, orion/hercules are horribly slow lately, it should only take a second for the gridgen test! I suspect the filesystem is acting up again because it seems to only go slow for the first time the test is run, when I try to re-run the test with `-V` to see what parts are going slow, it runs fine :man_shrugging:

**Review by Dooruk — APPROVED** [review]
All good, thanks @travissluka ! All tests except 1 passed after I built `mom6.x` manually, that is A+ for SOCA.

Only failed test is `test_soca_convertstate_soca2cice` and I'm sure that is somehow @guillaumevernieres's fault...

.. no, just a reference fail.

**Comment by travissluka** [comment]
> All good, thanks @travissluka ! All tests except 1 passed after I built `mom6.x` manually, that is A+ for SOCA.
> 
> Only failed test is `test_soca_convertstate_soca2cice` and I'm sure that is somehow @guillaumevernieres's fault...
> 
> .. no, just a reference fail.

someday (soon??) I'll get around to making icepack part of the CI so that test gets tested again, I keep forgetting about it.
Also I just added  https://github.com/JCSDA-internal/soca/issues/1039

**Pull request merged**
