### PR TITLE
Allow multiple communicators

### LINKED ISSUE #210: Pass communicators in geometry down to lower levels
To complete #208

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
Finishing the work started in #208 : Pass the mpi communicator to the lower fortran levels.

**What bug does it fix, or what feature does it add?**
This should allow the use of multiple communicators, required to implement some of the oops applications. This PR should allow the implementation of the change of resolution (#206, #339 ), and EDA, possibly, unless I forgot something ...

Is a change of answers expected from this PR? **No**

### Issue(s) addressed
- closes #210 

## Testing
How were these changes tested? **Using the current ctests**
What compilers / HPCs was it tested with? **gcc 7.4, Intel 18**
Are the changes covered by ctests? **yes**

## Dependencies
None

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@travissluka : The tests are ok with gcc 7.4. Is there a reason why we run with such an old version of gcc with travis-ci? Copy/paste from the build:
```
$ g++ --version
$g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
```

I'll do some testing with intel, but I can't reproduce the error that I see in travis-ci (add_incr and ens_hofx failing).

Update: Works fine with intel 18.

**Comment by travissluka** [comment]
> @travissluka : The tests are ok with gcc 7.4. Is there a reason why we run with such an old version of gcc with travis-ci? Copy/paste from the build:
> 
> ```
> $ g++ --version
> $g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
> ```
> 
> I'll do some testing with intel, but I can't reproduce the error that I see in travis-ci (add_incr and ens_hofx failing).
> 
> Update: Works fine with intel 18.

That's the gcc version of ubuntu on travis ci, not the one in the docker container, ignore that.

**Comment by travissluka** [comment]
hmm, weird, TravisCI is definitely not happy. I need to look into it more

**Comment by travissluka** [comment]
@guillaumevernieres 
I'm getting `enshofx` failure in debug mode for both intel19 and gcc on my machine now. Problem doesn't show up in release mode. (soca's current `develop` works fine)

**Comment by guillaumevernieres** [comment]
Humm ... Works for me in release and debug with gcc 7.4. I'll try with 19 tomorrow.

**Comment by guillaumevernieres** [comment]
@travissluka : Looks like it's finally ready for review.

**Review by travissluka — APPROVED** [review]

**Pull request merged**
