### PR TITLE
update ObsLocalization

### PR DESCRIPTION
**Pull request by travissluka**
## Description

Small change to keep up to date with obs localization changes in oops/ioda.
An `obslocalization` unit test was added, otherwise nothing new, no change in answers expected.

## Dependencies

Requires oops/ioda branches with same name
- waiting on https://github.com/JCSDA-internal/ioda/pull/170
- waiting on https://github.com/JCSDA-internal/oops/pull/1113

### CODE REVIEW

**Review by shlyaeva — APPROVED** [review]
thank you @travissluka!

**Comment by travissluka** [comment]
> thank you @travissluka!

luckily Lorenz decided to have a long nap this afternoon!

**Comment by shlyaeva** [comment]
> luckily Lorenz decided to have a long nap this afternoon

👶 😴  I hope that doesn't exclude good night sleep!

**Comment by shlyaeva** [comment]
oops and ioda PRs were merged, this is ready for merge now

**Pull request merged**
