### PR TITLE
feature/marineobs2ioda

### PR DESCRIPTION
**Pull request by aerorahul**
convert a batch of marine obs to ioda.
controlled via a yaml file.

will need more improvements, suggestions welcome.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
I'm OK with no test for now, but how about moving the script to /bin and call it soca_...?

**Comment by aerorahul** [comment]
@guillaumevernieres I agree with the name change.
As for tests, I intend to add tests in following PR with a cycling ability.

I will also add hgodas use case as well.

**Comment by aerorahul** [comment]
@guillaumevernieres script has been renamed.
@travissluka hgodas_*2ioda.py probably already reads the windowed data; i.e. it does not handle multiple input files for each day or hour for e.g.  I assume you are creating the files a-priori and this script simply converts format to ioda.

**Review by guillaumevernieres — APPROVED** [review]
All good.

**Pull request merged**
