### PR TITLE
Cleanup and Consistency

### PR DESCRIPTION
**Pull request by aerorahul**
- Fortran interfaces that were not modules have been made into modules.
- some interface modules were called `c_moduleName_mod`, others `moduleName_mod_c`.  They are now all consistently called `moduleName_mod_c`
- a structure is applied across all fortran files. All public elements are declared up at the top.
- use `linkedList` from OOPS. removed from SOCA.
- any `use` statement in a fortran module, now has to specify the element being used using the `only` statement; the exception being MPI, NetCDF, iso_c_binding.
- most changes are white-spaces being made consistent.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@aerorahul : Just tested, but I see you are still pushing commits. Since you are in a clean-up mode, could you move the use statements and implicit none to the top of the new modules, and remove the redundant implicit none in the subroutines ?

**Comment by aerorahul** [comment]
> @aerorahul : Just tested, but I see you are still pushing commits. Since you are in a clean-up mode, could you move the use statements and implicit none to the top of the new modules, and remove the redundant implicit none in the subroutines ?

done that already. Did you find something that I missed?

**Comment by guillaumevernieres** [comment]
> > @aerorahul : Just tested, but I see you are still pushing commits. Since you are in a clean-up mode, could you move the use statements and implicit none to the top of the new modules, and remove the redundant implicit none in the subroutines ?
> 
> done that already. Did you find something that I missed?

interface in geometry, model, balance, bkgerr, ...
it seems that use fckit_configuration_module, only: fckit_configuration is in the subroutine.

**Review by guillaumevernieres — APPROVED** [review]
pretty pretty ... fortran code norm next? @aerorahul , feel free to squash.

**Comment by guillaumevernieres** [comment]
@aerorahul : I noticed the issue in randon vec, any idea why? That change should have worked.

**Comment by aerorahul** [comment]
> > > @aerorahul : Just tested, but I see you are still pushing commits. Since you are in a clean-up mode, could you move the use statements and implicit none to the top of the new modules, and remove the redundant implicit none in the subroutines ?
> > 
> > 
> > done that already. Did you find something that I missed?
> 
> interface in geometry, model, balance, bkgerr, ...
> it seems that use fckit_configuration_module, only: fckit_configuration is in the subroutine.

Ok, yeah found them. done!
I think I am done with the cleanup.

> @aerorahul : I noticed the issue in randon vec, any idea why? That change should have worked.

no idea. The interface `random_c` requires the line `use iso_c_binding`.
We should move to using `random_mod.F90` from OOPS. Another PR for that and breaking Fortran.h into pieces e.g. GeometryFortran.h etc.

Also, Run/soca_setup.F90 is basically nothing. Needs cleanup.

We can handle all that in another PR.

**Review by travissluka — APPROVED** [review]
Since the tests pass, I approve, there is not enough coffee here for me to make it though 6k lines of changes. Thanks @aerorahul !

**Comment by aerorahul** [comment]
@travissluka [this](https://github.com/JCSDA/soca/pull/178/files?w=1) that will bring 6k down to approx. 800. Enough coffee for that?

**Comment by guillaumevernieres** [comment]
@aerorahul , I am reluctant to merge, since you've been pushing commits after my first approval ... Agree with the fortran.h, doing it the same way @danholdaway has it in fv3 seem cleaner. It's done in a few places, but not most ... Good luck @aerorahul :)

**Comment by aerorahul** [comment]
> @aerorahul , I am reluctant to merge, since you've been pushing commits after my first approval ... Agree with the fortran.h, doing it the same way @danholdaway has it in fv3 seem cleaner. It's done in a few places, but not most ... Good luck @aerorahul :)

I am following your suggestions on removing the unnecessary implicits and moving use statements up.
But, I agree, not good on my part to push after reviewer has reviewed.  I will issue a PR, when all is done and set.

**Comment by travissluka** [comment]
@aerorahul 
Huh, how have I gone this long without knowing about the "hide whitespace changes" option?

**Pull request merged**
