### PR TITLE
BUMP major upgrade for the static B

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Companion PR of https://github.com/JCSDA-internal/saber/pull/85, see this PR for details.
It also solves the issue of redundant points detection for 1/4 degree runs.

### Issue(s) addressed

None.

## Acceptance Criteria (Definition of Done)

Reasonable modifications of test reference values.

## Dependencies

Waiting on the following PRs:
- [x] waiting on https://github.com/JCSDA-internal/saber/pull/85

## Impact

None.

## Test Data

None.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@clouden90 @jkbk2004 , FYI these branches have the fix that you need to run the 3dvar with the 1/4 deg grid. I tested it on my side but could you test as well?

**Comment by clouden90** [comment]
> @clouden90 @jkbk2004 , FYI these branches have the fix that you need to run the 3dvar with the 1/4 deg grid. I tested it on my side but could you test as well?

@guillaumevernieres. Thx. I used this branch and ran a few cycles of 3dvar with 1/4deg setup. So far looks ok!

**Comment by guillaumevernieres** [comment]
> > @clouden90 @jkbk2004 , FYI these branches have the fix that you need to run the 3dvar with the 1/4 deg grid. I tested it on my side but could you test as well?
> 
> @guillaumevernieres. Thx. I used this branch and ran a few cycles of 3dvar with 1/4deg setup. So far looks ok!

Thanks for the info @clouden90 . One of the UFO filter that we use for adt is currently not working ()https://github.com/JCSDA-internal/soca-science/issues/256), so your run will eventually go to "lala" land. We'll try to look into this issue next week.

**Comment by clouden90** [comment]
@guillaumevernieres . Thx. I noticed that, too. Plus the 1/4deg 3dvar is way more expensive than 1-deg case., so right now I only assimilate with insitu profiles first to get some ideas. But good to know that you will try to attack [JCSDA-internal/soca-science#256](https://github.com/JCSDA-internal/soca-science/issues/256) soon.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres . Thx. I noticed that, too. Plus the 1/4deg 3dvar is way more expensive than 1-deg case., so right now I only assimilate with insitu profiles first to get some ideas. But good to know that you will try to attack [JCSDA-internal/soca-science#256](https://github.com/JCSDA-internal/soca-science/issues/256) soon.

@clouden90 yes, sorry. The slowness is in the process of being addressed ...

**Comment by guillaumevernieres** [comment]
@benjaminmenetrier Are you planning to merge the sabre `feature/vbal_computation_nn_interpolation` branch soon?
btw: I updated most of the reference file, I stopped the ci test because I still need to update a bump yaml file that is missing the number of levels (`nl`).

**Comment by benjaminmenetrier** [comment]
Not soon, but not too late I hope...

**Comment by benjaminmenetrier** [comment]
Closing temporarily to avoid spamming...

**Pull request closed without merging**
