### PR TITLE
Feature/auto update geometry info

### PR DESCRIPTION
**Pull request by weihuang-jedi**
## Description

https://github.com/JCSDA-internal/oops/pull/1776 broke our LETKF ctests.

The following tests FAILED:
	 70 - test_soca_letkf_split_observer (Failed)
	 71 - letkf_split_observer_post (Failed)
	 72 - test_soca_letkf_split_solver (Failed)

We need to change the yaml file as 'update obs config with geometry info' is set to true as default in OOPS.

### Issue(s) addressed

- fixes JCSDA/soca-bundle/issues/774

## Testing

Run the above ctest, and pass.

## Dependencies

-  JCSDA/oops/pull/1776 (this PR already merged into develop).

### CODE REVIEW

**Comment by travissluka** [comment]
you're using `release/stable_nightly`. don't do that. rebase on `develop`

**Comment by weihuang-jedi** [comment]
OK, let me switch to develop.

**Comment by weihuang-jedi** [comment]
Updated to develop branch, but still got error:

68: Run: Finishing oops::LocalEnsembleDA<SOCA, UFO and IODA observations>
with status = 0
68: terminate called after throwing an instance of
'oops::TestReferenceFloatMismatchError'
68:   what():  Test reference Float mismatch @ Line:5
68: Test Val : -2.8387699999999999e-01
68: Ref  Val : -2.8387745530822628e-01
68: Delta    : 4.5530822628814249e-07
68: Relative tolerance: 2.8387722765411317e-07
68: Absolute tolerance: 0.0000000000000000e+00
68: Test Line: '    ssh   min=   -1.899558   max=    0.906722   mean=
-0.283877'
68: Ref Line : '    ssh   min=-1.8995576445088340   max=0.9067222046846501
  mean=-0.2838774553082263'
68: srun: error: Orion-01-34: task 0: Aborted
68: srun: launch/slurm: _step_signal: Terminating StepId=6216309.0
68: slurmstepd: error: *** STEP 6216309.0 ON Orion-01-34 CANCELLED AT
2022-07-14T13:16:58 ***
68: srun: error: Orion-01-34: task 1: Terminated
68: srun: Force Terminated StepId=6216309.0
1/3 Test #68: test_soca_letkf ..................***Failed   19.17 sec
test 69
    Start 69: test_soca_letkf_split_observer



69: Run: Finishing oops::LocalEnsembleDA<SOCA, UFO and IODA observations>
with status = 0
69: terminate called after throwing an instance of
'oops::TestReferenceFloatMismatchError'
69:   what():  Test reference Float mismatch @ Line:5
69: Test Val : -2.8387699999999999e-01
69: Ref  Val : -2.8387745337608961e-01
69: Delta    : 4.5337608961526499e-07
69: Relative tolerance: 2.8387722668804483e-07
69: Absolute tolerance: 0.0000000000000000e+00
69: Test Line: '    ssh   min=   -1.899558   max=    0.906722   mean=
-0.283877'
69: Ref Line : '    ssh   min=-1.8995576445088340   max=0.9067222046846501
  mean=-0.2838774533760896'
69: srun: error: Orion-01-34: task 0: Aborted
69: srun: launch/slurm: _step_signal: Terminating StepId=6216310.0
69: slurmstepd: error: *** STEP 6216310.0 ON Orion-01-34 CANCELLED AT
2022-07-14T13:16:59 ***
69: srun: error: Orion-01-34: task 1: Terminated
69: srun: Force Terminated StepId=6216310.0
2/3 Test #69: test_soca_letkf_split_observer ...***Failed    1.70 sec
test 71
    Start 71: test_soca_letkf_split_solver


71: NOTE from PE     0: close_param_file: MOM_input has been closed
successfully.
71: Geometry: Global tree size = 2520, footprint = 161280
71: Exception:  Reason: H5Fopen failed
71:     compat: HDF5_Version_Range: [V110, Latest (1.12.0)]
71:     filename:       ./Data/sst.letkf.observer.nc
71:     mode:   ioda::Engines::BackendOpenModes::Read_Only
71:     source_column:  0
71:     source_filename:
 /work/noaa/gsienkf/weihuang/jedi/src/src.soca/soca/bundle/ioda/src/engines/ioda/src/ioda/Engines/HH/HH.cpp
71:     source_function:        ioda::Group
ioda::Engines::HH::openFile(const std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char>> &,
ioda::Engines::BackendOpenModes, std::pair<ioda::Engines::HH::HDF5_Version,
ioda::Engines::HH::HDF5_Version>)
71:     source_line:    167
71:
71: Exception: oops::LocalEnsembleDA<SOCA, UFO and IODA observations>
terminating...
71: Exception:  Reason: H5Fopen failed
71:     compat: HDF5_Version_Range: [V110, Latest (1.12.0)]
71:     filename:       ./Data/sst.letkf.observer.nc
71:     mode:   ioda::Engines::BackendOpenModes::Read_Only
71:     source_column:  0
71:     source_filename:
 /work/noaa/gsienkf/weihuang/jedi/src/src.soca/soca/bundle/ioda/src/engines/ioda/src/ioda/Engines/HH/HH.cpp
71:     source_function:        ioda::Group
ioda::Engines::HH::openFile(const std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char>> &,
ioda::Engines::BackendOpenModes, std::pair<ioda::Engines::HH::HDF5_Version,
ioda::Engines::HH::HDF5_Version>)
71:     source_line:    167
71:
71: Exception: oops::LocalEnsembleDA<SOCA, UFO and IODA observations>
terminating...
71: terminate called after throwing an instance of
'oops::TestReferenceMissingTestLineError'
71:   what():  TestReference: Missing test output line corresponding to
reference file Line#:1
71: Ref line: 'Initial state for member 1:'
71: srun: error: Orion-01-34: task 0: Aborted
71: srun: launch/slurm: _step_signal: Terminating StepId=6216311.0
71: slurmstepd: error: *** STEP 6216311.0 ON Orion-01-34 CANCELLED AT
2022-07-14T13:17:01 ***
71: srun: error: Orion-01-34: task 1: Terminated
71: srun: Force Terminated StepId=6216311.0
3/3 Test #71: test_soca_letkf_split_solver .....***Failed    1.53 sec


So, ctest 68, 69 failed because of test did not match reference, and 71
failed as missing file.

**Comment by travissluka** [comment]
@weihuang-jedi the fact that the reference test numbers are trunctated indicates you are using an old version of oops. that was changed a long time ago.
```
68: Test Line: '    ssh   min=   -1.899558   max=    0.906722   mean=-0.283877'
68: Ref Line : '    ssh   min=-1.8995576445088340   max=0.9067222046846501
```

Look at the submitted changes  you have for `bundle/CMakeLists.txt`. Those should not be there, you should not be using tagged versions of the upstream repos. This is because you have not applied the changes on develop branch.

I'm closing this PR. it is fixed with https://github.com/JCSDA-internal/soca/pull/776

**Pull request closed without merging**
