### PR TITLE
Feature/geometry

### PR DESCRIPTION
**Pull request by clouden90**
Remove hardcoded file name for geometry #313
Description:
The soca_gridgen.x application generates a file soca_gridspec.nc that is subsequently read for the initialization of the Geometry class throughout soca. This currently prohibits using 2 different geometries which will be needed to resolve issue #309 .
Solution:
Pass the name of the gridspec file through the yaml config file.
Modifications have been made in soca_geom_mod.F90 & gridgen.yml & soca_mom6.F90 &convertstate.yml.
user-defined grid file name: geom_grid_file & user-defined param filename:  param_file have been added.

### Issue(s) addressed
- fixes #<313>

## Testing
These changes have been tested with Test case: test_soca_gridgen on Hera and it passed.

## Dependencies
None

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Thanks @clouden90 , I'll look at it later today or tomorrow. No need to copy/paste what is written in the issue, the link is enough, but do follow the PR template.
It looks like some of the tests are failing, I haven't had time to investigate, but you might need to merge develop into your branch. I could be wrong, but I don't think you needed to touch anything on the model side.

**Comment by guillaumevernieres** [comment]
@clouden90 , Your branch is up to date with develop, so ignore my previous comment.
You need to run all the tests before you submit your pr, sorry, I should have told you.

**Comment by clouden90** [comment]
Thanks, @guillaumevernieres. I have tried to run the whole tests related to soca. But even without my modifications, Some of the tests are still failing on Hera with intel/18.0.5.274 and jedi-stack/intel-impi-18.0.5. These test cases are listed below:

The following tests FAILED:
         28 - test_soca_dirac_socahyb_cov (Failed)
         36 - test_soca_3dhyb (Failed)
         37 - test_soca_3dhybfgat (Failed)

**Comment by guillaumevernieres** [comment]
> Thanks, @guillaumevernieres. I have tried to run the whole tests related to soca. But even without my modifications, Some of the tests are still failing on Hera with intel/18.0.5.274 and jedi-stack/intel-impi-18.0.5. These test cases are listed below:
> 
> The following tests FAILED:
> 28 - test_soca_dirac_socahyb_cov (Failed)
> 36 - test_soca_3dhyb (Failed)
> 37 - test_soca_3dhybfgat (Failed)

Develop works fine, just tested a few mn ago.

**Comment by clouden90** [comment]
> > Thanks, @guillaumevernieres. I have tried to run the whole tests related to soca. But even without my modifications, Some of the tests are still failing on Hera with intel/18.0.5.274 and jedi-stack/intel-impi-18.0.5. These test cases are listed below:
> > The following tests FAILED:
> > 28 - test_soca_dirac_socahyb_cov (Failed)
> > 36 - test_soca_3dhyb (Failed)
> > 37 - test_soca_3dhybfgat (Failed)
> 
> Develop works fine, just tested a few mn ago.

Thx @guillaumevernieres. I redo the tests using  the JEDI Container with gnu compiler and openmpi. This time both Develop & my branch (feature/geometry) can pass all  tests:

Singularity jedi-gnu-openmpi-dev_latest.sif:~/work/my_build/soca> ctest
Test project /home/vagrant/work/my_build/soca
      Start  1: soca_coding_norms
 1/40 Test  #1: soca_coding_norms ...................   Passed    3.38 sec
      Start  2: test_soca_gridgen
 2/40 Test  #2: test_soca_gridgen ...................   Passed    1.08 sec
      Start  3: test_soca_forecast_identity
 3/40 Test  #3: test_soca_forecast_identity .........   Passed    1.12 sec
      Start  4: test_soca_forecast_identity_cice
 4/40 Test  #4: test_soca_forecast_identity_cice ....   Passed    1.02 sec
      Start  5: test_soca_forecast_mom6
 5/40 Test  #5: test_soca_forecast_mom6 .............   Passed    2.43 sec
      Start  6: test_soca_static_socaerror_init
 6/40 Test  #6: test_soca_static_socaerror_init .....   Passed    5.03 sec
      Start  7: test_soca_enspert
 7/40 Test  #7: test_soca_enspert ...................   Passed    5.22 sec
      Start  8: test_soca_geometry
 8/40 Test  #8: test_soca_geometry ..................   Passed    0.31 sec
      Start  9: test_soca_geometry_iterator
 9/40 Test  #9: test_soca_geometry_iterator .........   Passed    0.57 sec
      Start 10: test_soca_geometryatm
10/40 Test #10: test_soca_geometryatm ...............   Passed    0.35 sec
      Start 11: test_soca_state
11/40 Test #11: test_soca_state .....................   Passed    0.52 sec
      Start 12: test_soca_model
12/40 Test #12: test_soca_model .....................   Passed    2.41 sec
      Start 13: test_soca_modelaux
13/40 Test #13: test_soca_modelaux ..................   Passed    0.32 sec
      Start 14: test_soca_increment
14/40 Test #14: test_soca_increment .................   Passed    0.70 sec
      Start 15: test_soca_errorcovariance
15/40 Test #15: test_soca_errorcovariance ...........   Passed    1.27 sec
      Start 16: test_soca_linearmodel
16/40 Test #16: test_soca_linearmodel ...............   Passed    1.66 sec
      Start 17: test_soca_varchange_ana2model
17/40 Test #17: test_soca_varchange_ana2model .......   Passed    0.59 sec
      Start 18: test_soca_varchange_balance
18/40 Test #18: test_soca_varchange_balance .........   Passed    0.67 sec
      Start 19: test_soca_varchange_balance_TSSSH
19/40 Test #19: test_soca_varchange_balance_TSSSH ...   Passed    0.62 sec
      Start 20: test_soca_varchange_bkgerrfilt
20/40 Test #20: test_soca_varchange_bkgerrfilt ......   Passed    0.49 sec
      Start 21: test_soca_varchange_horizfilt
21/40 Test #21: test_soca_varchange_horizfilt .......   Passed    0.51 sec
      Start 22: test_soca_varchange_bkgerrsoca
22/40 Test #22: test_soca_varchange_bkgerrsoca ......   Passed    0.78 sec
      Start 23: test_soca_varchange_bkgerrgodas
23/40 Test #23: test_soca_varchange_bkgerrgodas .....   Passed    4.62 sec
      Start 24: test_soca_varchange_vertconv
24/40 Test #24: test_soca_varchange_vertconv ........   Passed    1.01 sec
      Start 25: test_soca_ensvariance
25/40 Test #25: test_soca_ensvariance ...............   Passed    0.90 sec
      Start 26: test_soca_parameters_bump_loc
26/40 Test #26: test_soca_parameters_bump_loc .......   Passed    1.95 sec
      Start 27: test_soca_ensrecenter
27/40 Test #27: test_soca_ensrecenter ...............   Passed    1.30 sec
      Start 28: test_soca_dirac_soca_cov
28/40 Test #28: test_soca_dirac_soca_cov ............   Passed    2.64 sec
      Start 29: test_soca_dirac_socahyb_cov
29/40 Test #29: test_soca_dirac_socahyb_cov .........   Passed    3.62 sec
      Start 30: test_soca_dirac_horizfilt
30/40 Test #30: test_soca_dirac_horizfilt ...........   Passed    0.51 sec
      Start 31: test_soca_hofx_3d
31/40 Test #31: test_soca_hofx_3d ...................   Passed    0.82 sec
      Start 32: test_soca_hofx_4d
32/40 Test #32: test_soca_hofx_4d ...................   Passed    1.89 sec
      Start 33: test_soca_enshofx
33/40 Test #33: test_soca_enshofx ...................   Passed    1.50 sec
      Start 34: test_soca_3dvar_soca
34/40 Test #34: test_soca_3dvar_soca ................   Passed    5.37 sec
      Start 35: test_soca_3dvar_godas
35/40 Test #35: test_soca_3dvar_godas ...............   Passed    6.34 sec
      Start 36: test_soca_3dvarfgat
36/40 Test #36: test_soca_3dvarfgat .................   Passed    6.86 sec
      Start 37: test_soca_3dhyb
37/40 Test #37: test_soca_3dhyb .....................   Passed   10.11 sec
      Start 38: test_soca_3dhybfgat
38/40 Test #38: test_soca_3dhybfgat .................   Passed   13.11 sec
      Start 39: test_soca_checkpointmodel
39/40 Test #39: test_soca_checkpointmodel ...........   Passed    1.00 sec
      Start 40: test_soca_convertstate
40/40 Test #40: test_soca_convertstate ..............   Passed    0.49 sec

100% tests passed, 0 tests failed out of 40

Label Time Summary:
executable    =  17.40 sec*proc (17 tests)
mpi           =  17.40 sec*proc (17 tests)
script        =  77.69 sec*proc (23 tests)
soca          =  95.09 sec*proc (40 tests)

Total Test time (real) =  95.16 sec

**Pull request closed without merging**
