### PR TITLE
Bugfix/recursive default

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
@aerorahul 
Merged develop and clone recursively by default in prep.sh.

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
Not sure what atlas geometry is being used in soca for. 
Jo seems quite a bit off.

**Comment by guillaumevernieres** [comment]
@aerorahul , I was hopping it would trigger a travis-ci build/test, I guess not. The --recursive should fix the issue.

**Comment by guillaumevernieres** [comment]
> Not sure what atlas geometry is being used in soca for.
> Jo seems quite a bit off.

@benjaminmenetrier 's pr that was merged a few days ago. Using atlas for B.

**Comment by benjaminmenetrier** [comment]
@aerorahul: SOCA used some FCKIT functions for geometry operations (like great-circle calculations) that I had implemented in the JCSDA fork. However, ECMWF people prefer to keep the geometry stuff in ATLAS instead of FCKIT, so we now use the `atlas_geometry` object.

**Comment by aerorahul** [comment]
> @aerorahul: SOCA used some FCKIT functions for geometry operations (like great-circle calculations) that I had implemented in the JCSDA fork. However, ECMWF people prefer to keep the geometry stuff in ATLAS instead of FCKIT, so we now use the `atlas_geometry` object.

@benjaminmenetrier thanks for the info. doesn’t eckit have distance methods ? Just curious

**Comment by benjaminmenetrier** [comment]
You are right, I think that `atlas` calls to sphere distance or kdtrees are just pretty C++ and Fortran wrapper of `eckit` functions.

**Pull request merged**
