### PR TITLE
 Bugfix for the mask_check option

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Companion PR of https://github.com/JCSDA-internal/saber/pull/149, more details there.

### Issue(s) addressed

Issue in SABER repo.

## Testing

Tested on my workstation (GNU-OpenMPI).
I added two new dirac tests with specifically chosen points to ensure the `mask_check` option was working as intended.

## Dependencies

- waiting on https://github.com/JCSDA-internal/saber/pull/149

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
I wonder if we should have an ensemble generation that is not dependent on bump for our ctests ... Something to think about a day other than today.
Thanks for the fix @benjaminmenetrier

**Comment by benjaminmenetrier** [comment]
Finally working, should we merge this today? I can merge the SABER PR anytime.

**Comment by guillaumevernieres** [comment]
> Finally working, should we merge this today? I can merge the SABER PR anytime.

Go for it @benjaminmenetrier !

**Comment by benjaminmenetrier** [comment]
SABER PR merged, you can go ahead with this one.

**Pull request merged**
