### PR TITLE
Addition of an error trap when attempting to use SocaError with u, v

### LINKED ISSUE #586: Error trap for covariance model
## Description
We are missing an error trap when a user is specifying `uocn, vocn` and using the `SocaError` static covariance model.

## Solution
To inform the user of the current issue, abort when `SocaError` is used with `uocn, vocn`.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
closes #586

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
@lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet

**Comment by lliu1220** [comment]
> @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet

@guillaumevernieres 
thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.

**Comment by lliu1220** [comment]
> > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> 
> @guillaumevernieres
> thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.


Shoot, just saw this!! i hope not...

    case('tocn', 'socn', 'ssh', 'chl', 'biop') 
       init_ocean = .true.     case('uocn', 'vocn')      
  **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")     end select**

**Comment by lliu1220** [comment]
> > > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> > 
> > 
> > @guillaumevernieres
> > thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.
> 
> Shoot, just saw this!! i hope not...
> 
> case('tocn', 'socn', 'ssh', 'chl', 'biop')
> ```
>    init_ocean = .true.     case('uocn', 'vocn')      
> ```
> 
> **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.") end select**

@guillaumevernieres 
simple, why couldn't we just:

on Line 93, modify code to:

do ivar = 1, self%vars%nvars()
     case('cicen','hicen')
      init_seaice = .true.
     case('tocn', 'socn', 'uocn','vocn','ssh', 'chl', 'biop')
      init_ocean = .true.

remove Ling 99-100
call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")

**Comment by lliu1220** [comment]
> @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet

@guillaumevernieres 
LIne 155
case ('tocn', 'socn', 'uocn','vocn', 'ssh', 'sw', 'lw', 'lhf', 'shf', 'us', 'chl', 'biop')

Line 189, add 

 case ('u/vocn')      
scale = self%pert_scale%S      
conv =&gt; self%ocean_conv(1)
 
then uocn vocn covariance will be calculated!

**Comment by guillaumevernieres** [comment]
> > > > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> > > 
> > > 
> > > @guillaumevernieres
> > > thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.
> > 
> > 
> > Shoot, just saw this!! i hope not...
> > case('tocn', 'socn', 'ssh', 'chl', 'biop')
> > ```
> >    init_ocean = .true.     case('uocn', 'vocn')      
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.") end select**
> 
> @guillaumevernieres
> simple, why couldn't we just:
> 
> on Line 93, modify code to:
> 
> do ivar = 1, self%vars%nvars()
> case('cicen','hicen')
> init_seaice = .true.
> case('tocn', 'socn', 'uocn','vocn','ssh', 'chl', 'biop')
> init_ocean = .true.
> 
> remove Ling 99-100
> call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")

u and v are on different grids, so no, we cannot do what you suggest. All the tools are there to do the work, from the rotation to the field interpolation, we just need to decide how we want our increments geometry to look like and add a step in the workflow to apply the rotation, which is not done in the 3dvar.

**Comment by lliu1220** [comment]
> > > > > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> > > > 
> > > > 
> > > > @guillaumevernieres
> > > > thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.
> > > 
> > > 
> > > Shoot, just saw this!! i hope not...
> > > case('tocn', 'socn', 'ssh', 'chl', 'biop')
> > > ```
> > >    init_ocean = .true.     case('uocn', 'vocn')      
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.") end select**
> > 
> > 
> > @guillaumevernieres
> > simple, why couldn't we just:
> > on Line 93, modify code to:
> > do ivar = 1, self%vars%nvars()
> > case('cicen','hicen')
> > init_seaice = .true.
> > case('tocn', 'socn', 'uocn','vocn','ssh', 'chl', 'biop')
> > init_ocean = .true.
> > remove Ling 99-100
> > call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")
> 
> u and v are on different grids, so no, we cannot do what you suggest. All the tools are there to do the work, from the rotation to the field interpolation, we just need to decide how we want our increments geometry to look like and add a step in the workflow to apply the rotation, which is not done in the 3dvar.

@guillaumevernieres 
thanks.
how about letkf, was it arranged in a more reasonable increment geometry yet? 
just want to see the big pic.
thanks.

**Comment by lliu1220** [comment]
> > > > > > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> > > > > 
> > > > > 
> > > > > @guillaumevernieres
> > > > > thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.
> > > > 
> > > > 
> > > > Shoot, just saw this!! i hope not...
> > > > case('tocn', 'socn', 'ssh', 'chl', 'biop')
> > > > ```
> > > >    init_ocean = .true.     case('uocn', 'vocn')      
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.") end select**
> > > 
> > > 
> > > @guillaumevernieres
> > > simple, why couldn't we just:
> > > on Line 93, modify code to:
> > > do ivar = 1, self%vars%nvars()
> > > case('cicen','hicen')
> > > init_seaice = .true.
> > > case('tocn', 'socn', 'uocn','vocn','ssh', 'chl', 'biop')
> > > init_ocean = .true.
> > > remove Ling 99-100
> > > call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")
> > 
> > 
> > u and v are on different grids, so no, we cannot do what you suggest. All the tools are there to do the work, from the rotation to the field interpolation, we just need to decide how we want our increments geometry to look like and add a step in the workflow to apply the rotation, which is not done in the 3dvar.
> 
> @guillaumevernieres
> thanks.
> how about letkf, was it arranged in a more reasonable increment geometry yet?
> just want to see the big pic.
> thanks.

@guillaumevernieres 
also one more question.
what was the error estimate for my current 3dvar uocn vocn assimilation.
they truly indeed work. which is 'amazing' giving their 'non-covariance' exit, i was amazed by soca still able to do the work even if... 
so , how devastating it is, as is.?

**Comment by guillaumevernieres** [comment]
@lliu1220 I think it was pointed out earlier by @travissluka . B for u and v is the identity, so 1 obs for u or v = 3 grid points filled. 
This PR is only addressing the issue when running the 3dvar, not the letkf. 

PS: Nothing special about soca, it's just an interface to jedi.

**Comment by lliu1220** [comment]
> 1 obs for u or v = 3 grid points filled.

@guillaumevernieres 
B for u and v is the identity,-- at least I got that right- so I know I wasn't completely wrong.
1 obs for u or v=3 grid points filled is mystical.
no. everything special about soca, it's a myth.

**Review by lliu1220 — APPROVED** [review]

**Comment by lliu1220** [comment]
> > > > > @lliu1220 , @yongzuo123 , have a look at soca_covariance_mod.f90, hopefully it should make sense why u, v should not be part of your control variables for the 3dvar ... yet
> > > > 
> > > > 
> > > > @guillaumevernieres
> > > > thank you for getting back to us. the code is 400 lines, is there a specific segment you want me to pay attention to save me some time? thanks for your guidance. I'm sure there are a lot unknown to me as profound as SOCA as always.
> > > 
> > > 
> > > Shoot, just saw this!! i hope not...
> > > case('tocn', 'socn', 'ssh', 'chl', 'biop')
> > > ```
> > >    init_ocean = .true.     case('uocn', 'vocn')      
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.") end select**
> > 
> > 
> > @guillaumevernieres
> > simple, why couldn't we just:
> > on Line 93, modify code to:
> > do ivar = 1, self%vars%nvars()
> > case('cicen','hicen')
> > init_seaice = .true.
> > case('tocn', 'socn', 'uocn','vocn','ssh', 'chl', 'biop')
> > init_ocean = .true.
> > remove Ling 99-100
> > call abor1_ftn("soca_covariance: No covariance model for (u, v) yet.")
> 
> u and v are on different grids, so no, we cannot do what you suggest. All the tools are there to do the work, from the rotation to the field interpolation, we just need to decide how we want our increments geometry to look like and add a step in the workflow to apply the rotation, which is not done in the 3dvar.

@guillaumevernieres 
if you choose to assimilate UV instead of speed, then you do not need to worry about rotation of velocity toward model grid, the only thing you need to deal with is observation error covariance due to 6 km average bin
Then my 3dvar estimate error would only source from interpolation offset, given tidal impact as well as how noisy these velocity data are, I would say my initial results aren't bad at all.

**Review by travissluka — APPROVED** [review]
Ultimately there should be a `default` to catch any arbitrary variable that isn't handled. But we can worry about that when this code gets generalized a bit more later.

**Pull request merged**
